// packages/renderer/src/pages/modal/Profile.vue
<script setup lang="ts">
import { mdiClose, mdiCog, mdiGithub, mdiLogout } from '@mdi/js'
import { useIpcRenderer } from '@vueuse/electron'
import { storeToRefs } from 'pinia'
import { computed } from 'vue'
import { useRouter } from 'vue-router'

import { useUserStore } from '@/store/user'
import type { Account } from '@/types'
import is from '@/util/is'
const userStore = useUserStore()
const router = useRouter()
const { account } = storeToRefs(userStore)

const profile = computed((): Account['profile'] | undefined => {
  return account.value?.profile
})

const props = defineProps({
  modelValue: Boolean,
})

const emit = defineEmits(['update:modelValue'])

const show = computed<boolean>({
  get() {
    return props.modelValue
  },
  set(value) {
    emit('update:modelValue', value)
  },
})

const goto = (url: string) => {
  if (is.electron()) {
    const ipcRenderer = useIpcRenderer()
    ipcRenderer.invoke('open-url', url)
  } else {
    window.open(url, '_blank')
  }
}

function dispatch(type: string) {
  switch (type) {
    case 'sign_out':
      signOut()
      show.value = false
      break
    case 'settings':
      show.value = false
      router.push('/setting')
      break
  }
}
const signOut = () => {
  userStore.signOut()
}
</script>
<template>
  <v-dialog v-model="show">
    <v-card flat color="surface" width="420" min-height="450" rounded="lg">
      <div class="px-2 pt-2">
        <v-btn icon @click="show = false">
          <v-icon> {{ mdiClose }}</v-icon>
        </v-btn>
      </div>

      <v-list-item v-if="profile">
        <v-badge content="vip" color="primary" location="bottom end">
          <!-- <template v-if="profile.vipType === 11" #badge>
            <v-img :src="vipPicUrl" :min-width="16"></v-img>
          </template> -->
          <v-avatar size="56">
            <v-img :src="profile.avatarUrl" />
          </v-avatar>
        </v-badge>
        <div class="ml-6">
          <v-list-item-title>{{ profile.nickname }}</v-list-item-title>
          <v-list-item-subtitle class="text-caption"> {{ profile.signature }}</v-list-item-subtitle>
          <v-btn class="mt-2" variant="outlined" size="small" @click="goto('https://music.163.com/#/user/update')">
            {{ $t('main.setting.manage_account') }}
          </v-btn>
        </div>
      </v-list-item>
      <v-divider class="my-2" />
      <v-list-item dense class="px-6" @click="dispatch('settings')">
        <v-list-item-icon :icon="mdiCog"> </v-list-item-icon>
        <v-list-item-title class="ml-4"> {{ $t('common.setting') }} </v-list-item-title>
      </v-list-item>
      <v-list-item dense class="px-6" @click="dispatch('sign_out')">
        <v-list-item-icon :icon="mdiLogout"> </v-list-item-icon>
        <v-list-item-title class="ml-4">{{ $t('message.logout') }}</v-list-item-title>
      </v-list-item>
      <div class="mt-auto py-2">
        <span class="d-flex justify-center align-center">
          <v-btn variant="text" size="small"> {{ $t('message.disclaimer') }} </v-btn>
          ·
          <v-btn
            variant="text"
            size="small"
            class="d-flex align-center"
            @click="goto('https://github.com/GuMengYu/v-player')"
            ><v-icon small>{{ mdiGithub }}</v-icon> github</v-btn
          >
        </span>
      </div>
    </v-card>
  </v-dialog>
</template>

// src/pages/modal/Profile.tsx
import {
  Avatar,
  Box,
  Button,
  Card,
  Divider,
  IconButton,
  Typography, styled, useTheme,
} from '@mui/material'
import { useMemo } from 'react'
import {
  Close,
  EditRounded,
  Logout as LogoutIcon,
} from '@mui/icons-material'
import { ipcRenderer } from 'electron'
import * as React from 'react'
import Md3Dialog from './Md3Dialog'
import { useUserStore } from '@/store/user'
import { useAppStore } from '@/store/app'
import is from '@/util/is'

function Profile() {
  const { showProfile: open, toggleProfile } = useAppStore()
  const { account } = useUserStore()
  const theme = useTheme()
  const avatarUrl = useMemo(() => {
    return account?.profile.avatarUrl
  }, [account])

  const BottomButton = styled(Button)(() => ({
    'flex': 1,
    'height': 60,
    'boxShadow': 'none',
    'border': '1px solid transparent',
    'justifyContent': 'start',
    'gap': 4,
    '&:hover': {
      bgcolor: theme.palette.secondaryContainer.main,
      borderColor: theme.palette.primary.main,
    },
  }))
  BottomButton.defaultProps = {
    variant: 'contained',
    color: 'surface' as 'primary',
    disableElevation: true,
  }
  const goto = (url: string) => {
    if (is.electron())
      ipcRenderer.invoke('open-url', url)
    else
      window.open(url, '_blank')

  }
  function handleClose() {
    toggleProfile(false)
  }
  function handleLogout() {
    ipcRenderer.invoke('reset-direct')
    localStorage.clear()
    location.reload()
    // ipcRenderer.invoke('relaunch-direct')
  }
  function handleEdit() {
    ipcRenderer.invoke('open-url', 'https://music.163.com/#/user/update')
  }
  return (
    <Md3Dialog open={open} onClose={handleClose}>
      <Card
        sx={{
          width: 400,
          p:1,
          bgcolor: theme.palette.surface.main,
          color: theme.palette.onSurface.main,
        }}
      >
        <Box display="flex" justifyContent="end">
          <IconButton onClick={handleClose}>
            <Close />
          </IconButton>
        </Box>
        <Box
          sx={{
            position: 'relative',
            px: 1,
          }}
        >
          <Card
            variant="outlined"
            sx={{
              height: 92,
              bgcolor: theme.palette.surfaceVariant.main,
              display: 'flex',
              justifyContent: 'start',
              alignItems: 'center',
              borderRadius: 4,
              px: 2,
            }}
          >
            <Avatar
              sx={{
                height: 56,
                width: 56,
                mr: 2,
              }}
              src={avatarUrl}
            ></Avatar>
            <Box>
              <Typography variant="h6">{account?.profile.nickname}</Typography>
              <Typography variant="caption" className="line-clamp-1">
                {account?.profile.signature}
              </Typography>
            </Box>
          </Card>
          {/*<Button*/}
          {/*  variant="contained"*/}
          {/*  color="primary"*/}
          {/*  sx={{*/}
          {/*    height: 48,*/}
          {/*    width: 48,*/}
          {/*    borderRadius: 3.5,*/}
          {/*    minWidth: 48,*/}
          {/*    position: 'absolute',*/}
          {/*    bottom: -26,*/}
          {/*    right: 25,*/}
          {/*  }}*/}
          {/*  onClick={handleEdit}*/}
          {/*>*/}
          {/*  <EditRounded />*/}
          {/*</Button>*/}
        </Box>
        <Box
          sx={{
            mt: 2,
            px: 1,
            display: 'flex',
            justifyContent: 'space-between',
            gap: 0.5,
          }}
        >
          <BottomButton
            sx={{
              borderTopLeftRadius: 30,
              borderBottomLeftRadius: 30,
            }}
          >
            <EditRounded  fontSize='small' />
            <Typography variant="caption">编辑资料 </Typography>
          </BottomButton>
          <BottomButton
            sx={{
              borderTopRightRadius: 30,
              borderBottomRightRadius: 30,
            }}
            onClick={handleLogout}
          >
            <LogoutIcon fontSize='small' />
            <Typography variant="caption">退出登录 </Typography>
          </BottomButton>
        </Box>
        <Box display="flex" justifyContent="center" mt={2} gap={1}>
          <Button
            variant="text"
            size="small"
            onClick={() => goto('https://github.com/GuMengYu/music-you/blob/dev/README.md#声明')}
          >
            <Typography variant="caption">免责声明 </Typography>
          </Button>
          <Divider orientation='vertical' flexItem variant='middle' />
          <Button
            size="small"
            variant="text"
            onClick={() => goto('https://github.com/GuMengYu/music-you')}
          >
            <Typography variant="caption">github </Typography>
          </Button>
        </Box>
      </Card>
    </Md3Dialog>
  )
}

export default Profile
