// src/components/BackToTop.tsx
import { Button, Zoom } from '@mui/material'
import { useLayoutEffect, useState } from 'react'
import KeyboardArrowUpIcon from '@mui/icons-material/KeyboardArrowUp'

export default function BackToTop() {
  const [main, setMain] = useState<HTMLElement | null>(null)
  const [show, setShow] = useState(false)
  const onScroll = (e: any) => {
    setShow(e.target.scrollTop > 68)
  }
  useLayoutEffect(() => {
    const el = document.getElementById('app-main-content')
    el?.addEventListener('scroll', onScroll)
    setMain(el)
    return () => {
      el?.removeEventListener('scroll', onScroll)
    }
  }, [])
  return <div className='absolute bottom-20 right-4 z-50'>
    {
      <Zoom
        in={show}
      >
        <Button
          variant={'contained'}
          color={'primaryContainer' as 'primary'}
          className='no-drag-area'
          sx={{
            height: 50,
            width: 50,
            borderRadius: 3.5,
            minWidth: 50,
          }}
          onClick={() => {
            main.scrollTo({
              top: 0,
              behavior: 'smooth',
            })
          }}
        >
          <KeyboardArrowUpIcon color={'onPrimaryContainer' as 'primary'} />
        </Button>
      </Zoom>

    }
  </div>
}

// src/components/button/BackToTop.vue
<template>
  <div class="ma-4 position-absolute" :style="btnStyle">
    <v-fab-transition>
      <v-square-btn
        v-show="model"
        variant="flat"
        class="mt-auto pointer-events-initial"
        color="primaryContainer"
        size="x-large"
        elevation="8"
        rounded="lg"
        @click="onClick"
      >
        <v-icon>
          {{ mdiChevronUp }}
        </v-icon>
      </v-square-btn>
    </v-fab-transition>
  </div>
</template>

<script setup lang="ts">
import { mdiChevronUp } from '@mdi/js'
import { storeToRefs } from 'pinia'

import { useSettingStore } from '@/store/setting'
const { miniPlayer } = storeToRefs(useSettingStore())
const model = ref(false)
const main = ref()
onMounted(() => {
  main.value = document.getElementById('v-player-content')
  if (main.value) {
    main.value.addEventListener('scroll', onScroll)
  }
})
onUnmounted(() => {
  main.value.removeEventListener('scroll', onScroll)
})
const btnStyle = computed(() => {
  return {
    right: 0,
    bottom: `${miniPlayer.value ? 16 : 88}px`,
  }
})
function onScroll() {
  model.value = main.value.scrollTop > 68
}

function onClick() {
  main.value.scrollTo({
    top: 0,
    behavior: 'smooth',
  })
}
</script>

<style scoped>
.pointer-events-none {
  pointer-events: none;
}

.pointer-events-initial {
  pointer-events: initial;
}
</style>
