// src/components/app/cover/Cover.vue
<template>
  <v-hover v-slot="{ isHovering, props }">
    <v-card
        class="cover-container"
        :rounded="rounded"
        flat
        color="surfaceVariant"
        :class="{ 'on-hover': isHovering }"
        :elevation="isHovering ? 1 : 0"
        v-bind="props"
        :max-width="$attrs.maxWidth"
        :max-height="$attrs.maxHeight"
    >
      <v-img
          class="cover-image"
          :class="`rounded-${rounded}`"
          cover
          :src="coverBgUrl"
          :aspect-ratio="1"
      >
        <div class="d-flex flex-fill fill-height align-end pa-2">
          <transition
              name="slide-fade"
          >
            <v-btn
                @click.prevent="play"
                icon color="primary" v-if="isHovering">
              <v-icon color="onPrimary">{{
                  mdiPlay
                }}
              </v-icon>
            </v-btn>
          </transition>
        </div>
      </v-img>
      <v-card-title v-if="!noInfo" :class="`h-${titleLine}x`" class="text-subtitle-1 text-onSurfaceVariant">
        <router-link
            :to="`/playlist/${data.id}`"
            class="text-onSurfaceVariant text-decoration-none">
          {{ data.name }}
        </router-link>
      </v-card-title>
      <v-card-subtitle v-if="!noInfo && subTitle" class="text-subtitle-2 pb-4">
        <span class="h-1x" v-if="subTitle">
          {{ subTitle }}
        </span>
      </v-card-subtitle>
      <slot/>
    </v-card>
  </v-hover>
</template>
<script setup lang="ts">
import {computed, ref} from "vue";

import {mdiPlay} from '@mdi/js';

import {usePlayer} from "@/player/player";

import {sizeOfImage} from '@util/fn';
import {getPlayList, getAlbum, getArtist} from '@api/index';
import {getList} from "@api/music";


const player = usePlayer()
const loading = ref<boolean>(false)
const props = defineProps({
  data: {
    type: Object,
    default: () => ({}),
  },
  rounded: {
    type: [String, Boolean],
    default: 'lg',
  },
  type: {
    type: String,
    default: 'album',
    require: true,
  },
  titleLine: {
    type: Number,
    default: 1,
  },
  subTitle: {
    type: String,
    default: "",
  },
  noInfo: {
    type: Boolean,
    default: false,
  },
  extra: {
    type: String,
    default: null,
  },
});

const coverBgUrl = computed(() => {
  return sizeOfImage(props.data.picUrl ?? props.data.coverImgUrl, 1024);
})
const subTitle = computed(() => {
  return props.extra ?? props.data.copywriter;
})

const to = computed(() => {
  return {
    album: `/album/${props.data.id}`,
    playlist: `/playlist/${props.data.id}`,
    artist: `/artist/${props.data.id}`,
  }[props.type];
})

const service = computed(() => {
  return {
    album: getAlbum,
    playlist: getPlayList,
    artist: getArtist,
  }[props.type];
})

async function play() {
  loading.value = true;
  try {
    const info = await getList(props.type, props.data.id);
    const track = await player.updatePlayList(info);
    await player.updatePlayerTrack(track.id);
  } catch (e) {
    console.log(e);
  } finally {
    loading.value = false;
  }
}

</script>
<style scoped lang="scss">
.cover-container {
  cursor: pointer;
  .cover-image {
    border-bottom-left-radius: initial !important;
    border-bottom-right-radius: initial !important;
  }
}
.slide-fade-enter-active,
.slide-fade-leave-active {
  transition: all 0.3s cubic-bezier(1, .17, 0, 1.49);
}

.slide-fade-enter-from,
.slide-fade-leave-to {
  transform: translateY(20px);
  opacity: 0;
}

.rounded-lg {
  border-radius: 12px !important;
}
</style>

// src/components/cover/Cover.tsx
import {
  Box,
  Card,
  CardContent,
  Typography,
  useTheme,
} from '@mui/material'
import { useCallback, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { useNavigate } from 'react-router-dom'
import { sizeOfImage, sleep, toHttps } from '@/util/fn'
import Image from '@/components/Image'
import { getTrackList } from '@/api/music'
import { usePlayerControl } from '@/hooks/usePlayer'
import { PlayIcon } from '@/components/icons/icons'
import LoadingButton from '@/components/button/LoadingButton'

function Cover({ data, subTitle, type, inset }: {
  data: any
  subTitle?: string
  type: 'album' | 'playlist'
  inset?: boolean
}) {
  const theme = useTheme()
  const coverBgUrl = sizeOfImage(toHttps(data.picUrl ?? data.coverImgUrl))
  const _subTitle = subTitle ?? data.copywriter
  const [isHovering, setIsHovering] = useState(false)
  const { addToQueueAndPlay } = usePlayerControl()
  const [loading, setLoading] = useState(false)

  const navigate = useNavigate()

  function jumpTo() {
    navigate(`/${type}/${data.id}`)
  }

  const handlePlay = useCallback(async (e: any) => {
    e.stopPropagation()
    try {
      setLoading(true)
      await sleep(2000)
      const info = await getTrackList(type, data.id)
      addToQueueAndPlay(info.tracks, info.id, type, data.name)
      setLoading(false)
    }
    catch (e) {
      console.log(e)
    }
  }, [type, data])

  return (
    <Card
      elevation={isHovering ? 1 : 0}
      sx={{
        borderRadius: 4,
        bgcolor: theme.palette.surfaceVariant.main,
        color: theme.palette.onSurfaceVariant.main,
      }}
      className="cursor-pointer"
      onMouseEnter={() => setIsHovering(true)}
      onMouseLeave={() => setIsHovering(false)}
      onClick={jumpTo}
    >
      <Box>
        <Box
          sx={{
            position: 'relative',
            aspectRatio: 1,
          }}
        >
          {/* <CardMedia
            component="img"
            image={coverBgUrl}
            sx={{ aspectRatio: 1 / 1, borderRadius: 4 }}
          ></CardMedia> */}
          <Image src={coverBgUrl} className="absolute"
            gradient={inset ? `linear-gradient(360deg, ${theme.palette.surface.main}e6 0%, rgb(0 0 0 / 0%) 100%)` : ''}/>
          <div className='absolute top-0 flex h-full w-full'>
            {
              inset && (<Box className='flex items-end pr-16 py-4 pl-2' sx={{
                color: theme.palette.onSurface.main,
              }}>
                <Typography className="line-clamp-2" variant="subtitle2">
                  {data.name}
                </Typography>
              </Box>)
            }
            <AnimatePresence>
              {isHovering && (
                <motion.div
                  initial={{
                    opacity: 0,
                    position: 'absolute',
                    bottom: 0,
                    padding: 16,
                    right: 0,
                    transform: 'translateY(20px)',
                  }}
                  animate={{
                    opacity: 1,
                    transform: 'translateY(0px)',
                  }}
                  exit={{
                    opacity: 0,
                    transform: 'translateY(20px)',
                  }}
                  transition={{
                    duration: 0.35,
                    ease: [0.34, 1.56, 0.64, 1],
                  }}
                >
                  <LoadingButton
                    loading={loading}
                    sx={{
                      'p': 0,
                      'bgcolor': `${theme.palette.primary.main}66`,
                      '&:hover': {
                        bgcolor: `${theme.palette.primary.main}4D`,
                      },
                    }}
                    onClick={handlePlay}
                  >
                    <PlayIcon sx={{ fontSize: '2.5rem' }} color='primary'/>
                  </LoadingButton>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

        </Box>
        {
          !inset && <CardContent sx={{ px: 1.5 }}>
            <Typography className="line-clamp-1" variant="subtitle2">
              {data.name}
            </Typography>
            <Typography className="line-clamp-1" variant="body2">
              {_subTitle}
            </Typography>
          </CardContent>
        }
      </Box>
    </Card>
  )
}

export { Cover }
