// src/components/cover/VideoCover.tsx
import {
  Box, IconButton,
  Typography,
  useTheme,
} from '@mui/material'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { isArray } from 'lodash'
import { AnimatePresence, motion } from 'framer-motion'
import { formatNumber, toHttps } from '@/util/fn'
import Image from '@/components/Image'
import ArtistLink from '@/components/links/artist'
import { PlayIcon } from '@/components/icons/icons'

function VideoCover({ data }: {
  data: any
}) {
  const theme = useTheme()
  const coverBgUrl = toHttps(data.picUrl ?? data.cover ?? data.coverUrl ?? data.imgurl16v9)
  const id = data.id ?? data.vid
  const [isHovering, setIsHovering] = useState(false)

  const navigate = useNavigate()

  const artists = useMemo(() => {
    if (data.artistId) {
      return [
        {
          userId: data.artistId,
          userName: data.artistName,
        },
      ]
    }
    if (data.artists && data.artists.length)
      return data.artists

    if (data.creator) {
      if (isArray(data.creator))
        return data.creator
      else
        return [data.creator]
    }
    return []
  }, [data])
  function jumpTo() {
    navigate(`/video/${id}`)
  }

  return (
    <Box
      sx={{
        bgcolor: 'transparent',
      }}
      className="cursor-pointer"

    >
      <Box>
        <Box
          onMouseEnter={() => setIsHovering(true)}
          onMouseLeave={() => setIsHovering(false)}
          sx={{
            position: 'relative',
            aspectRatio: 16 / 9,
            overflow: 'hide',
          }}
          onClick={jumpTo}

        >
          <Image fit='cover' src={coverBgUrl} className="absolute rounded-lg" />
          <div className='absolute top-0 flex h-full w-full'>
            <AnimatePresence>
              {isHovering && (
                <motion.div
                  initial={{
                    opacity: 0,
                    position: 'absolute',
                    bottom: 0,
                    padding: 16,
                    right: 0,
                    transform: 'translateY(20px)',
                  }}
                  animate={{
                    opacity: 1,
                    transform: 'translateY(0px)',
                  }}
                  exit={{
                    opacity: 0,
                    transform: 'translateY(20px)',
                  }}
                  transition={{
                    duration: 0.35,
                    ease: [0.34, 1.56, 0.64, 1],
                  }}
                >
                  <IconButton
                    sx={{
                      'p': 0,
                      'bgcolor': `${theme.palette.primary.main}66`,
                      '&:hover': {
                        bgcolor: `${theme.palette.primary.main}4D`,
                      },
                    }}
                    onClick={jumpTo}
                  >
                    <PlayIcon sx={{ fontSize: '2.5rem' }} color='primary'/>
                  </IconButton>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </Box>
        <Box sx={{ p: 0.5 }}>
          <Typography className="line-clamp-1" variant="subtitle2">
            {data.name ?? data.title}
          </Typography>
          <div className='flex justify-between items-center'>
            <Typography className="line-clamp-1" variant="caption">
              <ArtistLink artist={artists} />
            </Typography>
            <Typography variant="caption">
              {formatNumber(data.playCount ?? data.playTime)}
            </Typography>

          </div>

        </Box>
      </Box>
    </Box>
  )
}

export default VideoCover

// src/components/cover/VideoCover.vue
<template>
  <div class="cover-container">
    <v-hover v-slot="{ isHovering, props }">
      <v-card rounded="lg" class="d-flex align-end justify-end cover-card" flat :to="`/video/${id}`" v-bind="props">
        <v-img :aspect-ratio="16 / 9" :src="coverBgUrl" class="cover-img align-end" :lazy-src="placeholderUrl" cover>
          <div class="d-flex flex-fill fill-height align-end pa-2">
            <transition name="slide-fade-y">
              <v-btn
                v-if="isHovering"
                icon
                color="primary"
                size="small"
                elevation="0"
                class="cover-btn"
                :class="{ 'hover-btn': isHovering }"
              >
                <v-icon>{{ icon.mdiPlay }}</v-icon>
              </v-btn>
            </transition>
          </div>
        </v-img>
      </v-card>
    </v-hover>
    <span class="line-clamp-1 mt-2 text-caption text--primary">
      {{ title }}
    </span>
    <span class="line-clamp-1 text-caption">
      <artists-link :artists="artists" />
      {{ count && $t('main.play_count', [count]) }}
    </span>
  </div>
</template>
<script lang="ts">
import { mdiPlay } from '@mdi/js'
import { isArray } from 'lodash-es'
import { defineComponent } from 'vue'

import placeholderUrl from '@/assets/placeholder.png'
import { formatNumber, sizeOfImage, toHttps } from '@/util/fn'
export default defineComponent({
  name: 'VideoCover',
  props: {
    data: {
      type: Object,
      default: () => ({}),
    },
  },
  data() {
    return {
      icon: {
        mdiPlay,
      },
      placeholderUrl,
    }
  },
  computed: {
    id() {
      return this.data.id ?? this.data.vid ?? ''
    },
    title() {
      return this.data.name ?? this.data.title ?? ''
    },
    subTitle() {
      return this.data.copywriter
    },
    artists() {
      if (this.data.artistId) {
        return [
          {
            userId: this.data.artistId,
            userName: this.data.artistName,
          },
        ]
      }
      if (this.data.artists && this.data.artists.length) {
        return this.data.artists
      }
      if (this.data.creator) {
        if (isArray(this.data.creator)) {
          return this.data.creator
        } else {
          return [this.data.creator]
        }
      }
      return []
    },
    coverBgUrl() {
      return sizeOfImage(toHttps(this.data.picUrl ?? this.data.cover ?? this.data.coverUrl ?? this.data.imgurl16v9))
    },
    count() {
      return formatNumber(this.data.playCount ?? this.data.playTime)
    },
  },
  methods: {},
})
</script>

<style lang="scss" scoped>
.cover-container {
  .title {
    text-decoration: none;
    &:hover {
      text-decoration: underline;
    }
  }
  .cover-card {
    .cover-actions {
      justify-content: space-between;
      .hover-btn {
        backdrop-filter: blur(30px) brightness(90%);
        background: transparent;
      }
      .cover-btn:hover {
        background: var(--v-theme-primary);
        transform: scale(1.1);
        transition: 0.3s all ease-in-out;
      }
    }
    .cover-img {
      border-radius: inherit;
      z-index: 1;
    }
  }
}
</style>
