// src/components/cover/Cover.tsx
import {sizeOfImage, toHttps} from "@/util/fn";
import {
  Box,
  Card,
  CardContent,
  IconButton,
  Typography,
  useTheme,
} from "@mui/material";
import {useState} from "react";
import {AnimatePresence, motion} from "framer-motion";
import {PlayArrow as PlayIcon, Pause as PauseIcon} from "@mui/icons-material";
import Image from "@/components/Image";
import {getTrackList} from "@/api/music";
import {playQueueStore} from "@/store/playQueue";
import {usePlayer} from "@/hooks/usePlayer";
import { useNavigate } from "react-router-dom";

const Cover = ({data, subTitle, type}: { data: any; subTitle?: string; type: 'album' | 'playlist' }) => {
  const theme = useTheme();
  const coverBgUrl = sizeOfImage(toHttps(data.picUrl ?? data.coverImgUrl));
  const _subTitle = subTitle ?? data.copywriter;
  const [isHovering, setIsHovering] = useState(false);
  const {updatePlayQueue} = playQueueStore()
  const {player} = usePlayer()
  const [loaded, setLoaded] = useState(false)
  const navigate = useNavigate()
  function jumpTo() {
    navigate(`/playlist/${data.id}`,)
  }

  async function handlePlay() {
    try {
      const info = await getTrackList(type, data.id)
      updatePlayQueue(info.id, type, data.name, info.tracks)
      player.next()
      setLoaded(true)
    } catch (e) {
      console.log(e)
    }
  }

  return (
    <Card
      elevation={isHovering ? 1 : 0}
      sx={{
        borderRadius: 4,
        bgcolor: theme.palette.surfaceVariant.main,
        color: theme.palette.onSurfaceVariant.main,
      }}
      className="cursor-pointer"
      onMouseEnter={() => setIsHovering(true)}
      onMouseLeave={() => setIsHovering(false)}
      onClick={jumpTo}
    >
      <Box>
        <Box
          sx={{
            position: "relative",
            aspectRatio: 1 / 1
          }}
        >
          {/* <CardMedia
            component="img"
            image={coverBgUrl}
            sx={{ aspectRatio: 1 / 1, borderRadius: 4 }}
          ></CardMedia> */}
          <Image src={coverBgUrl} className="absolute"/>

          <AnimatePresence>
            {isHovering && (
              <motion.div
                initial={{
                  opacity: 0,
                  position: "absolute",
                  bottom: 0,
                  padding: 8,
                  transform: "translateY(20px)",
                }}
                animate={{
                  opacity: 1,
                  transform: "translateY(0px)",
                }}
                exit={{
                  opacity: 0,
                  transform: "translateY(20px)",
                }}
                transition={{
                  duration: 0.35,
                  ease: [0.34, 1.56, 0.64, 1],
                }}
              >
                <IconButton
                  sx={{
                    bgcolor: theme.palette.primary.main,
                    color: theme.palette.onPrimary.main,
                    '&:hover': {
                      bgcolor: theme.palette.primaryContainer.main,
                      color: theme.palette.onPrimaryContainer.main,
                    }
                  }}
                  onClick={handlePlay}
                >
                  <PlayIcon sx={{fontSize: 36}}/>
                </IconButton>
              </motion.div>
            )}
          </AnimatePresence>
        </Box>
        <CardContent sx={{px: 1.5}}>
          <Typography className="line-clamp-1" variant="subtitle2">
            {data.name}
          </Typography>
          <Typography className="line-clamp-1" variant="body2">
            {_subTitle}
          </Typography>
        </CardContent>
      </Box>
    </Card>
  );
};

export {Cover};

// packages/renderer/src/components/cover/Cover.vue
<template>
  <v-hover v-slot="{ isHovering, props: hoverProps }">
    <v-card
      class="cover-container"
      :rounded="rounded"
      flat
      color="surfaceVariant"
      :class="{ 'on-hover': isHovering }"
      :elevation="isHovering ? 1 : 0"
      v-bind="hoverProps"
      :min-width="$attrs['min-width']"
      :max-width="$attrs['max-width']"
      :max-height="$attrs['max-height']"
      :min-height="$attrs['min-height']"
      :to="to"
    >
      <v-img
        :class="`rounded-${rounded} ${noInfo ? 'cover-image' : 'cover-image-with-info'}`"
        cover
        :src="coverBgUrl"
        :aspect-ratio="1"
        :lazy-src="placeholderUrl"
      >
        <div class="d-flex flex-fill fill-height align-end pa-2">
          <transition name="slide-fade-y">
            <v-btn v-if="isHovering" icon color="primary" @click.prevent="play">
              <v-icon color="onPrimary">{{ mdiPlay }} </v-icon>
            </v-btn>
          </transition>
        </div>
      </v-img>
      <v-card-title v-if="!noInfo" :class="`line-clamp-${titleLine}`" class="text-subtitle-2 text-onSurfaceVariant">
        <router-link :to="`/playlist/${data.id}`" class="text-onSurfaceVariant text-decoration-none">
          {{ data.name }}
        </router-link>
      </v-card-title>
      <v-card-subtitle v-if="!noInfo && subTitle" class="text-subtitle-2 pb-4">
        <span v-if="subTitle" class="line-clamp-1">
          {{ subTitle }}
        </span>
      </v-card-subtitle>
      <slot />
    </v-card>
  </v-hover>
</template>
<script setup lang="ts">
import { mdiPlay } from '@mdi/js'
import { computed, ref } from 'vue'

import { getTrackList } from '@/api/music'
import placeholderUrl from '@/assets/placeholder.png'
import { usePlayer } from '@/player/player'
import { usePlayQueueStore } from '@/store/playQueue'
import { sizeOfImage } from '@/util/fn'
const player = usePlayer()
const playQueue = usePlayQueueStore()
const loading = ref<boolean>(false)
const props = defineProps({
  data: {
    type: Object,
    default: () => ({}),
  },
  rounded: {
    type: [String, Boolean],
    default: 'lg',
  },
  type: {
    type: String,
    default: 'album',
    require: true,
  },
  titleLine: {
    type: Number,
    default: 1,
  },
  subTitle: {
    type: String,
    default: '',
  },
  noInfo: {
    type: Boolean,
    default: false,
  },
  extra: {
    type: String,
    default: null,
  },
})

const coverBgUrl = computed(() => {
  return sizeOfImage(props.data.picUrl ?? props.data.coverImgUrl)
})
const subTitle = computed(() => {
  return props.extra ?? props.data.copywriter
})

const to = computed(() => {
  return {
    album: `/album/${props.data.id}`,
    playlist: `/playlist/${props.data.id}`,
    artist: `/artist/${props.data.id}`,
  }[props.type]
})

async function play() {
  loading.value = true
  try {
    const info = await getTrackList(<'album' | 'playlist'>props.type, props.data.id)
    playQueue.updatePlayQueue(info.id, <'album' | 'playlist'>props.type, props.data.name, info.tracks)
    player.next()
  } catch (e) {
    console.log(e)
  } finally {
    loading.value = false
  }
}
</script>
<style scoped lang="scss">
.cover-container {
  .cover-image-with-info {
    border-bottom-left-radius: initial !important;
    border-bottom-right-radius: initial !important;
  }
}
</style>
