// src/pages/detail/Artist.tsx
import { Box, Button, DialogContent, DialogTitle, Divider, IconButton, Typography, useTheme } from '@mui/material'
import { useParams } from 'react-router-dom'
import QueueMusicIcon from '@mui/icons-material/QueueMusic'
import PlayArrowIcon from '@mui/icons-material/PlayArrow'
import MoreHorizIcon from '@mui/icons-material/MoreHoriz'
import ArrowCircleUpIcon from '@mui/icons-material/ArrowCircleUp'
import ArrowCircleDownIcon from '@mui/icons-material/ArrowCircleDown'

import ArrowForwardIcon from '@mui/icons-material/ArrowForward'
import { motion } from 'framer-motion'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useImmer } from 'use-immer'
import { useSnackbar } from 'notistack'
import { useCopyToClipboard } from 'react-use'
import { useTranslation } from 'react-i18next'
import Md3Dialog from '@/pages/modal/Md3Dialog'
import TrackList from '@/components/TrackList'
import PageTransition from '@/components/PageTransition'
import PlayListSkeleton from '@/pages/detail/PlayListSkeleton'
import type { Artist } from '@/types'
import Image from '@/components/Image'
import ImageViewer from '@/components/ImageViewer'
import useQueryArtist from '@/pages/detail/useQueryArtist'
import Col from '@/components/Col'
import GridRow from '@/components/GridRow'
import { Cover } from '@/components/cover/Cover'
import ArtistCover from '@/components/cover/ArtistCover'
import { useReplacePlayQueue } from '@/hooks/usePlayQueue'
import { useContextMenu } from '@/hooks/useContextMenu'
import { sub } from '@/api/music'

function Header({ artist, onPlay }: { artist: Artist | undefined; onPlay: () => void }) {
  const theme = useTheme()
  const [showDesc, setShowDesc] = useState(false)
  const [showImageView, setShowImageView] = useState(false)
  const { openContextMenu } = useContextMenu()
  const { enqueueSnackbar } = useSnackbar()
  const { t } = useTranslation()

  const [copied, copyToClipboard] = useCopyToClipboard()

  const [subscribed, setSubscribed] = useState(false)

  useEffect(() => {
    setSubscribed(artist.followed)
  }, [artist])

  async function subscribe() {
    const { code, message } = await sub('artist', artist.id, subscribed ? 0 : 1)
    if (code === 200) {
      enqueueSnackbar(`${subscribed ? t`message.remove_from_library_success` : t`message.add_library_success`}`, { variant: 'success' })
      setSubscribed(!subscribed)
    }
    else {
      enqueueSnackbar(message, { variant: 'error' })
    }
  }

  function handleMore(e: React.MouseEvent<HTMLElement>) {
    const items = [
      ...(subscribed
        ? [
            {
              type: 'item' as any,
              label: t`common.unfollow_artist`,
              onClick: () => {
                subscribe()
              },
            },
          ]
        : [
            {
              type: 'item' as any,
              label: t`common.follow_artist`,
              onClick: () => {
                subscribe()
              },
            },
          ]),
      {
        type: 'item' as any,
        label: t`common.check_cover`,
        onClick: () => {
          setShowImageView(true)
        },
      },
      {
        type: 'item' as any,
        label: t`common.copy_share`,
        onClick: () => {
          copyToClipboard(`https://music.163.com/#/playlist?id=${artist.id}`)
          enqueueSnackbar(t`message.copy_share_success`, { variant: 'success' })
        },
      },
    ]
    openContextMenu(e, items)
  }
  return (
    <motion.div
      initial={{
        opacity: 0, transform: 'translateX(15px)',
      }}
      animate={{
        opacity: 1, transform: 'translateX(0px)',
      }}
      transition={{
        duration: 0.25,
        ease: [0.34, 1.56, 0.64, 1],
      }}
    >
      <div className="flex flex-col">
        <div className="flex justify-between -ml-2 -mr-4 relative" style={{ height: '317px' }}>
          <Image
            className="absolute"
            src={artist.picUrl}
            fit="cover"
            gradient={`linear-gradient(90deg, ${theme.palette.surface.main} 0%, rgb(0 0 0 / 0%) 50%, ${theme.palette.surface.main}b3 100%), linear-gradient(360deg, ${theme.palette.surface.main} 0%, rgb(0 0 0 / 0%) 100%)`}
          />
          {
            artist?.picUrl
              && <ImageViewer open={showImageView} src={artist?.picUrl} onClose={() => setShowImageView(false)}/>
          }

          <div className="absolute h-full w-full flex flex-col">
            <div className="flex-1"></div>
            <div className="flex flex-col mx-3 mb-4 gap-2">
              <Typography variant="h4">{artist?.name}</Typography>
              <div className="flex flex-col">
                <Typography variant='body1'>
                  {artist.transNames.join('·')}
                  {artist.alias?.length ? `(${artist.alias.join('/')})` : ''}
                </Typography>
                <Typography variant='caption'>
                  {[...(artist['identifyTag'] ?? []), ...(artist['identities'] ?? [])].join('·')}
                </Typography>
              </div>
              <div className="flex py-2">
                <div
                  className="flex flex-col items-center px-4"
                  style={{ minWidth: '96px' }}
                >
                  <QueueMusicIcon fontSize='small'/>
                  <Typography variant="caption">{t`main.artists`}</Typography>
                </div>
                <Divider flexItem variant='middle' orientation="vertical"/>

                <div
                  className="flex flex-col items-center px-4"
                  style={{ minWidth: '96px' }}
                >
                  <Typography variant="body2">{t`main.tracks`}</Typography>
                  <Typography variant="caption">{artist.musicSize}</Typography>
                </div>
                <Divider flexItem variant='middle' orientation="vertical"/>
                <div
                  className="flex flex-col items-center px-4"
                  style={{ minWidth: '96px' }}
                >
                  <Typography variant="body2">{t`main.albums`}</Typography>
                  <Typography variant="caption">{artist.albumSize}</Typography>
                </div>
                <Divider flexItem variant='middle' orientation="vertical"/>
                <div
                  className="flex flex-col items-center px-4"
                  style={{ minWidth: '96px' }}
                >
                  <Typography variant="body2">{t`main.mvs`}</Typography>
                  <Typography variant="caption">{artist.mvSize}</Typography>
                </div>
              </div>
              <div className='flex gap-3'>
                <Button
                    disableElevation
                    variant='contained'
                    sx={{
                      'bgcolor': `${theme.palette.primary.main}1f`,
                      'color': theme.palette.primary.main,
                      'borderRadius': 2.5,
                      'px': 1.5,
                      'py': 1.5,
                      '&:hover': {
                        bgcolor: `${theme.palette.primary.main}38`,
                      },
                    }} onClick={onPlay}>
                  <PlayArrowIcon color='primary' className='mr-1' /> {t`common.play_all`}
                </Button>
                <IconButton size='large' sx={{
                  bgcolor: `${theme.palette.tertiary.main}1f`,
                }} onClick={handleMore}>
                  <MoreHorizIcon/>
                </IconButton>
              </div>
            </div>
          </div>
        </div>
        {
          artist?.briefDesc && <>
                <div className="flex flex-col gap-1">
                    <div className="flex items-center">
                        <Typography variant='body1'>{t`main.artist.desc`}</Typography>
                        <IconButton onClick={() => setShowDesc(true)}>
                            <ArrowForwardIcon/>
                        </IconButton>
                    </div>
                </div>
                <Md3Dialog fullWidth maxWidth='xs' open={showDesc} onClose={() => setShowDesc(false)}>
                    <DialogTitle variant='body1'>{t`main.artist.desc`}</DialogTitle>
                    <DialogContent>
                        <Typography variant='caption'>{artist.briefDesc}</Typography>
                    </DialogContent>
                </Md3Dialog>
            </>
        }
      </div>
    </motion.div>
  )
}

export default function ArtistPage() {
  const params = useParams()
  const { t } = useTranslation()
  const theme = useTheme()
  const { data, isLoading } = useQueryArtist(params.id)
  const [more, setMore] = useImmer({
    showMoreSong: false,
    showMoreAlbum: false,
    showMoreEps: false,
    showMoreCollection: false,
    showMoreMVs: false,
    showMoreDesc: false,
  })
  const albums = useMemo(() => data?.hotAlbums.filter(a => a.type === '专辑'), [data])
  const epAndSingle = useMemo(() => data?.hotAlbums.filter(a => ['EP/Single', 'EP', 'Single'].includes(a.type)), [data])
  const collection = useMemo(() => data?.hotAlbums.filter(a => a.type === '合集'), [data])

  const { replaceQueueAndPlay } = useReplacePlayQueue()
  const handlePlay = useCallback(() => {
    if (data.artist)
      replaceQueueAndPlay(data.hotSongs, data.artist.id, 'artist', data.artist.name)
  }, [data])
  return (
    <PageTransition>
      {isLoading}
      <Box sx={{ color: theme.palette.onSurface.main, display: 'flex', flexDirection: 'column', gap: 2 }} className='pr-2'>
        {
          isLoading ? <PlayListSkeleton/> : <Header artist={data.artist} onPlay={handlePlay}/>
        }
        {
          data?.hotSongs && <Col
                variant='body1'
                title={t`main.artist.hot`}
                more={
            <IconButton
              color='primary'
              onClick={() => {
                setMore((draft) => {
                  draft.showMoreSong = !draft.showMoreSong
                })
              }}>
                  {
                    more.showMoreSong ? <ArrowCircleUpIcon fontSize='small'/> : <ArrowCircleDownIcon fontSize='small'/>
                  }
                </IconButton>
          }
            >
                <TrackList tracks={more.showMoreSong ? data.hotSongs : data.hotSongs.slice(0, 5)} trackFrom={{ id: data.artist.id, name: data.artist.name, type: 'artist' }} />
            </Col>
        }

        {
          albums?.length && <Col title={t`main.artist.albums`} variant='body1' more={
            <IconButton
              color='primary'
              onClick={() => {
                setMore((draft) => {
                  draft.showMoreAlbum = !draft.showMoreAlbum
                })
              }}>
              {
                more.showMoreAlbum ? <ArrowCircleUpIcon fontSize='small'/> : <ArrowCircleDownIcon fontSize='small'/>
              }
            </IconButton>
          }>
            <GridRow>
              {
                (more.showMoreAlbum ? albums : albums.slice(0, 4))?.map((album) => {
                  return <Cover data={album} type={'album'} key={album.id} />
                })
              }
            </GridRow>
          </Col>
        }

        {
          epAndSingle?.length && <Col title={t`main.artist.epAndSingle`} variant='body1' more={
            <IconButton
              color='primary'
              onClick={() => {
                setMore((draft) => {
                  draft.showMoreEps = !draft.showMoreEps
                })
              }}>
              {
                more.showMoreEps ? <ArrowCircleUpIcon fontSize='small'/> : <ArrowCircleDownIcon fontSize='small'/>
              }
            </IconButton>
          }>
            <GridRow>
              {
                (more.showMoreEps ? epAndSingle : epAndSingle.slice(0, 4))?.map((album) => {
                  return <Cover data={album} type={'album'} key={album.id} />
                })
              }
            </GridRow>
          </Col>
        }
        {
          collection?.length
            ? <Col title={t`main.artist.collection`} variant='body1' more={
            <IconButton
              color='primary'
              onClick={() => {
                setMore((draft) => {
                  draft.showMoreCollection = !draft.showMoreCollection
                })
              }}>
              {
                more.showMoreCollection ? <ArrowCircleUpIcon fontSize='small'/> : <ArrowCircleDownIcon fontSize='small'/>
              }
            </IconButton>
          }>
            <GridRow>
              {
                (more.showMoreCollection ? collection : collection.slice(0, 4))?.map((album) => {
                  return <Cover data={album} type={'album'} key={album.id} />
                })
              }
            </GridRow>
          </Col>
            : null
        }
        {
          <Col title={t`main.artist.simi`}>
            <GridRow>
              {
                data?.simiArtists && data.simiArtists.map((artist) => {
                  return <ArtistCover data={artist} key={artist.id} compact />
                })
              }
            </GridRow>
          </Col>
        }

      </Box>
    </PageTransition>

  )
}

// src/pages/Artist.vue
<script lang="ts" setup>
import {
  mdiAccountMusic,
  mdiArrowDownCircleOutline,
  mdiArrowRight,
  mdiArrowRightCircleOutline,
  mdiArrowUpCircleOutline,
  mdiBookmarkPlusOutline,
  mdiBookmarkRemoveOutline,
  mdiClose,
  mdiPlayOutline,
} from '@mdi/js'
import dayjs from 'dayjs'
import { computed, reactive, watchEffect } from 'vue'
import { useI18n } from 'vue-i18n'
import { useToast } from 'vue-toastification'
import { useDisplay } from 'vuetify'

import { getArtist, getArtistAlbum, getArtistDetail, getArtistMv, getSimiArtist } from '@/api/artist'
import { sub } from '@/api/music'
import PinBtn from '@/components/button/PinBtn.vue'
import { usePlayer } from '@/player/player'
import { usePlayQueueStore } from '@/store/playQueue'
import { useSettingStore } from '@/store/setting'
import type { Album, Artist, MV, Track } from '@/types'
const toast = useToast()
const { t } = useI18n()
const { smAndUp } = useDisplay()
const settingStore = useSettingStore()

const theme = computed(() => {
  return settingStore.wallpaperColor + 'Dark'
})
const playQueue = usePlayQueueStore()
const player = usePlayer()
const props = defineProps({
  id: {
    type: [String, Number],
    default: '',
  },
})
useScrollToTop(0, () => props.id)

const loading = ref(false)
const followed = ref(false)
const playLoading = ref(false)
const more = ref({
  showMoreSong: false,
  showMoreAlbum: false,
  showMoreEps: false,
  showMoreCollection: false,
  showMoreMVs: false,
  showMoreDesc: false,
})
interface RootState {
  artist: Artist
  hotSongs: Track[]
  hotAlbums: Album[]
  mvs: MV[]
  simiArtists: Artist[]
}
const state: RootState = reactive({
  artist: {} as any,
  hotSongs: [],
  hotAlbums: [],
  mvs: [],
  simiArtists: [],
})

const albums = computed(() => state.hotAlbums.filter((a) => a.type === '专辑'))
const epAndSingle = computed(() => state.hotAlbums.filter((a) => ['EP/Single', 'EP', 'Single'].includes(a.type)))
const collection = computed(() => state.hotAlbums.filter((a) => a.type === '合集'))

watchEffect(() => {
  fetch(+props.id)
})
async function fetch(id: number) {
  loading.value = true
  try {
    const [artist, hotSong, album, mv, simiArtist] = await Promise.all([
      getArtistDetail(id),
      getArtist(id),
      getArtistAlbum(id),
      getArtistMv(id),
      getSimiArtist(id),
    ])
    state.artist = { ...artist?.data['artist'], ...hotSong['artist'] }
    state.hotSongs = hotSong['hotSongs'].slice(0, 20)
    state.hotAlbums = album['hotAlbums']
    state.mvs = mv['mvs']
    state.simiArtists = simiArtist['artists'].slice(0, 6)
    followed.value = hotSong['artist']?.['followed'] // 不知怎滴 来源在获取热门歌曲接口里面
  } finally {
    loading.value = false
  }
}
async function play() {
  playLoading.value = true
  playQueue.updatePlayQueue(state.artist.id, 'artist', state.artist.name, state.hotSongs)
  player.next()
  setTimeout(() => {
    playLoading.value = false
  }, 1000)
}
async function follow() {
  const { id } = state.artist
  const { code, message } = await sub('artist', id, followed.value ? 0 : 1)
  if (code === 200) {
    followed.value = !followed.value
    toast.success(t('message.follow_msg', followed.value ? 1 : 2))
  } else {
    toast.error(message)
  }
}
function formatDate(datetime: string | number, format = 'YYYY-MM-DD') {
  return dayjs(datetime).format(format)
}
</script>
<template>
  <section>
    <list-loader v-if="loading" artist />
    <div v-else class="d-flex flex-column gap-6">
      <div class="drag-area d-flex mx-n4 mt-n5" :class="smAndUp ? '' : 'flex-column'">
        <v-img
          :src="state.artist.picUrl"
          cover
          max-height="360"
          :aspect-ratio="28 / 9"
          :gradient="`90deg, rgba(var(--v-theme-surface), 1) 0%, rgb(0 0 0 / 0%) 50%, rgba(var(--v-theme-surface), 0.7) 100%`"
        >
          <div
            class="d-flex flex-column justify-start h-100"
            :class="smAndUp ? 'order-1' : 'order-2'"
            :style="{
              background: 'linear-gradient(360deg, rgba(var(--v-theme-surface), 1) 0%,rgba(0,0,0,0) 100%)',
            }"
          >
            <back-btn class="align-self-start mb-auto mx-4 mt-4" variant="tonal" color="primary" />
            <div class="no-drag-area">
              <div class="d-flex flex-column gap-2 mx-6 mb-2">
                <span
                  class="text-h4 text-lg-h3 text-xl-h3 text-xxl-h2 font-weight-medium line-clamp-2 select-text"
                  :class="{
                    'pr-6': smAndUp,
                    'text-center': !smAndUp,
                  }"
                  >{{ state.artist.name }}</span
                >
                <div class="d-flex flex-column">
                  <span class="d-flex align-center text-body-1 font-weight-medium">
                    {{ state.artist.transNames.join('·') }}
                    {{ state.artist.alias?.length ? `(${state.artist.alias.join('/')})` : '' }}
                  </span>
                  <span class="text-caption text-disabled">
                    {{ [...(state.artist['identifyTag'] ?? []), ...(state.artist['identities'] ?? [])].join('·') }}
                  </span>
                </div>
                <div class="d-flex py-2" :class="{ 'justify-center': !smAndUp }">
                  <div class="d-flex flex-column align-center pr-4" :style="{ minWidth: '96px' }">
                    <span class="text-body-1 font-weight-medium">
                      <v-icon size="small">{{ mdiAccountMusic }} </v-icon>
                    </span>
                    <span class="text-disabled text-caption">歌手</span>
                  </div>
                  <v-divider class="my-2" vertical />
                  <div class="d-flex flex-column align-center px-4" :style="{ minWidth: '96px' }">
                    <span class="text-body-1 font-weight-medium">{{ state.artist.musicSize }}</span>
                    <span class="text-disabled text-caption"> 歌曲 </span>
                  </div>
                  <v-divider class="my-2" vertical />

                  <div class="d-flex flex-column align-center px-4" :style="{ minWidth: '96px' }">
                    <span class="text-body-1 font-weight-medium">{{ state.artist.albumSize }}</span>
                    <span class="text-disabled text-caption">专辑</span>
                  </div>
                  <v-divider class="my-2" vertical />
                  <div class="d-flex flex-column align-center pl-4" :style="{ minWidth: '96px' }">
                    <span class="text-body-1 font-weight-medium">{{ state.artist.mvSize }}</span>
                    <span class="text-disabled text-caption">MV</span>
                  </div>
                </div>
                <div class="d-flex align-center">
                  <v-btn
                    size="large"
                    class="mr-4 px-10 rounded-pill"
                    variant="tonal"
                    color="primary"
                    :loading="playLoading as boolean"
                    @click="play"
                  >
                    <v-icon size="large">{{ mdiPlayOutline }}</v-icon>
                  </v-btn>
                  <v-btn class="mr-4" icon variant="tonal" color="tertiary" @click="follow">
                    <v-icon>
                      {{ followed ? mdiBookmarkRemoveOutline : mdiBookmarkPlusOutline }}
                    </v-icon>
                    <v-tooltip activator="parent" location="top">
                      {{ t('common.following', followed ? 2 : 1) }}
                    </v-tooltip>
                  </v-btn>
                  <pin-btn :data="state.artist" type="artist" />
                </div>
              </div>
            </div>
          </div>
        </v-img>
      </div>
      <div class="d-flex flex-column gap-6 mx-2">
        <div v-if="state.artist.briefDesc" class="d-flex flex-column">
          <div class="d-flex align-center">
            <span class="font-weight-medium mr-2 text-h6">{{ t('main.artist.about') }}</span>
            <v-btn icon variant="text" @click="more.showMoreDesc = true">
              <v-icon>{{ mdiArrowRight }}</v-icon>
            </v-btn>
          </div>
          <p class="text-caption line-clamp-3 select-text">
            {{ state.artist.briefDesc }}
          </p>
        </div>
        <Col :title="$t('main.artist.hot')">
          <track-list
            :id="state.artist.id"
            :tracks="more.showMoreSong ? state.hotSongs : state.hotSongs.slice(0, 5)"
            type="artist"
          ></track-list>
          <template #more>
            <v-btn
              v-if="state.hotSongs.length > 5"
              icon
              size="x-small"
              variant="tonal"
              color="tertiary"
              @click="more.showMoreSong = !more.showMoreSong"
            >
              <v-icon>
                {{ more['showMoreSong'] ? mdiArrowUpCircleOutline : mdiArrowDownCircleOutline }}
              </v-icon>
            </v-btn>
          </template>
        </Col>
        <Col v-if="albums.length" :title="$t('main.artist.albums')">
          <card-row>
            <cover
              v-for="item in more.showMoreAlbum ? albums : albums.slice(0, 7)"
              :key="item.id"
              :data="item"
              :extra="`${formatDate(item.publishTime)} · ${item['subType']}`"
            />
          </card-row>
          <template #more>
            <v-btn
              v-if="albums.length > 7"
              icon
              size="x-small"
              variant="tonal"
              color="tertiary"
              @click="more.showMoreAlbum = !more.showMoreAlbum"
            >
              <v-icon>
                {{ more['showMoreAlbum'] ? mdiArrowUpCircleOutline : mdiArrowDownCircleOutline }}
              </v-icon>
            </v-btn>
          </template>
        </Col>
        <Col v-if="epAndSingle.length" :title="$t('main.artist.epAndSingle')">
          <card-row>
            <cover
              v-for="item in more.showMoreEps ? epAndSingle : epAndSingle.slice(0, 7)"
              :key="item.id"
              :data="item"
              :extra="`${formatDate(item.publishTime)} · ${item.type} · ${item['subType']}`"
            />
          </card-row>
          <template #action>
            <v-btn
              v-if="epAndSingle.length > 7"
              variant="text"
              size="small"
              @click="more.showMoreEps = !more.showMoreEps"
            >
              {{ $t(`common.${more['showMoreEps'] ? 'collapse' : 'expand'}`) }}
            </v-btn>
          </template>
        </Col>
        <Col v-if="collection.length" :title="$t('main.artist.collection')">
          <card-row>
            <cover
              v-for="item in more.showMoreCollection ? collection : collection.slice(0, 7)"
              :key="item.id"
              :data="item"
              :extra="`${formatDate(item.publishTime)} · ${item.type} · ${item['subType']}`"
            />
          </card-row>
          <template #more>
            <v-btn
              v-if="collection.length > 7"
              icon
              size="x-small"
              variant="tonal"
              color="tertiary"
              @click="more.showMoreCollection = !more.showMoreCollection"
            >
              <v-icon>
                {{ more['showMoreCollection'] ? mdiArrowUpCircleOutline : mdiArrowDownCircleOutline }}
              </v-icon>
            </v-btn>
          </template>
        </Col>
        <Col :title="$t('main.artist.mv')">
          <card-row>
            <video-cover v-for="mv in more.showMoreMVs ? state.mvs : state.mvs.slice(0, 6)" :key="mv.id" :data="mv" />
          </card-row>
          <template #more>
            <v-btn
              v-if="state.mvs.length > 6"
              icon
              size="x-small"
              variant="tonal"
              color="tertiary"
              @click="more.showMoreMVs = !more.showMoreMVs"
            >
              <v-icon>
                {{ more['showMoreMVs'] ? mdiArrowUpCircleOutline : mdiArrowDownCircleOutline }}
              </v-icon>
            </v-btn>
          </template>
        </Col>
        <Col :title="$t('main.artist.simi')">
          <card-row>
            <artists-cover v-for="ar in state.simiArtists" :key="ar.id" :artist="ar" />
          </card-row>
        </Col>
      </div>

      <v-dialog v-model="more.showMoreDesc" :scrollable="true">
        <v-card color="surfaceVariant" rounded="xl" class="pb-4 align-self-center" width="90vw" max-width="450">
          <v-card-title>
            <div class="d-flex justify-space-between align-center">
              {{ t('main.artist.desc') }}
              <v-btn icon variant="text" @click="more.showMoreDesc = false">
                <v-icon>{{ mdiClose }}</v-icon>
              </v-btn>
            </div>
          </v-card-title>
          <v-card-text>
            {{ state.artist['briefDesc'] }}
          </v-card-text>
        </v-card>
      </v-dialog>
    </div>
  </section>
</template>
