// src/components/comment/CommentItem.vue
<script lang="ts" setup>
import { mdiDotsVertical } from '@mdi/js'
import dayjs from 'dayjs'

import placeHolderUrl from '@/assets/placeholder.png'
import type { Comment } from '@/types'
import { toHttps } from '@/util/fn'
// coding here
const props = defineProps<{
  comment: Comment
}>()

const avatarUrl = computed(() => toHttps(props.comment.user.avatarUrl))
function formatDate(datetime: string | number, format = 'LL') {
  return dayjs(datetime).format(format)
}
</script>
<template>
  <div>
    <header>
      <div class="d-flex justify-space-between">
        <div class="d-flex gap-3 align-center">
          <v-avatar size="32">
            <v-img :aspect-ratio="1" contain :lazy-src="placeHolderUrl" :src="avatarUrl" />
          </v-avatar>

          <span class="text-body-2 select-text">{{ comment.user.nickname }}</span>
        </div>
        <div>
          <v-btn icon variant="text"
            ><v-icon> {{ mdiDotsVertical }}</v-icon></v-btn
          >
        </div>
      </div>
      <div class="mt-2 text-caption">
        {{ formatDate(comment.time) }}
      </div>
    </header>

    <div class="mt-2 text-body-2 select-text">
      {{ comment.content }}
    </div>
    <slot />
  </div>
</template>

// apps/client/src/components/comment/CommentItem.tsx
import { Avatar, Divider, Typography } from '@mui/material'
import { Comment } from '@/types'
import { formatDate, sizeOfImage, toHttps } from '@/util/fn'

export default function CommentItem({ comment }: {
  comment: Comment
}) {
  const avatarUrl = toHttps( sizeOfImage(comment.user.avatarUrl, 256))
  const name = comment.user.nickname
  return <div className='py-2 flex flex-col gap-1'>
    <div>
      <div className="flex justify-between">
        <div className="flex gap-3 items-center">
          <Avatar alt={name} src={avatarUrl} />
          <Typography variant='body2'>{ comment.user.nickname }</Typography>
        </div>
      </div>
      <Typography variant='caption'>{ formatDate(comment.time) }</Typography>
    </div>
    <Typography variant='body2' className="select-text">
      { comment.content }
    </Typography>
    <Divider flexItem sx={{ mt: 2 }} />
  </div>
}
