// packages/renderer/src/components/TrackItem.vue
<script setup lang="ts">
import { mdiDotsHorizontal, mdiHeart, mdiHeartOutline, mdiPlay } from '@mdi/js'
import { storeToRefs } from 'pinia'
import { computed } from 'vue'
import { useToast } from 'vue-toastification'

import placeholderUrl from '@/assets/placeholder.png'
import { useUserStore } from '@/store/user'
import type { Artist, Track } from '@/types'
import { formatDuring, sizeOfImage } from '@/util/fn'

const toast = useToast()
const userStore = useUserStore()

const { logged, account } = storeToRefs(userStore)
const props = defineProps({
  track: {
    type: Object,
    default: () => ({}),
  },
  type: {
    type: String,
    default: 'album',
  },
  index: {
    type: [String, Number],
    default: 0,
  },
  own: {
    type: Boolean,
    default: false,
  },
})

const likeLoading = ref(false)

const liked = computed(() => {
  return !!userStore.likes.find((id) => id === props.track.id)
})
const artists = computed(() => {
  const { ar, artists } = props.track
  const art = ar ?? artists ?? []
  return art.map((i: Artist) => ({ id: i.id, name: i.name }))
})
const album = computed(() => props.track.al ?? props.track.album ?? {})
const albumCover = computed(() => sizeOfImage(album.value.picUrl ?? album.value.coverImgUrl, 128))
const className = computed(() => {
  if (props.type !== 'album') {
    return 'track-item'
  } else {
    return 'track-item album-item'
  }
})
const isVip = computed(() => account.value?.profile.vipType === 11)
const available = computed(() => {
  if (props.track.fee === 1) {
    if (logged.value && isVip.value) {
      return {
        enable: true,
      }
    } else {
      return {
        enable: false,
        text: 'VIP用户可用',
      }
    }
  } else if (props.track.fee === 4) {
    return {
      text: '付费专辑，先购买',
      enable: false,
    }
  } else if (props.track.noCopyrightRcmd) {
    return {
      text: '无版权',
      enable: false,
    }
  } else {
    return {
      enable: true,
    }
  }
})
const emit = defineEmits<{
  (
    event: 'openctxmenu',
    payload: {
      x: number
      y: number
      track: Track
      liked: boolean
    }
  ): void
  (event: 'play', id: number): void
}>()
function play() {
  emit('play', props.track?.id)
}
function openMenu(e: MouseEvent) {
  emit('openctxmenu', {
    x: e.x,
    y: e.y,
    track: props.track as Track,
    liked: liked.value,
  })
}
async function toggleLike() {
  likeLoading.value = true
  const before = liked.value

  const success = await userStore.favSong(props.track.id, !liked.value)
  if (success) {
    if (before) {
      toast.success('已从"喜欢的音乐"移除')
    } else {
      toast.success('已添加至"喜欢的音乐"')
    }
  } else {
    toast.error('操作频繁或者网络出现错误')
  }
  likeLoading.value = false
}
</script>
<template>
  <v-hover v-slot="{ isHovering, props: _props }">
    <v-list-item
      v-bind="_props"
      rounded="lg"
      class="pa-0"
      active-color="primary"
      :value="track.id"
      @dblclick="play"
      @contextmenu.prevent="openMenu"
    >
      <div
        class="px-2 rounded-lg"
        :title="available.enable ? '' : available.text"
        :class="{ [className]: true, unavailable: !available.enable }"
      >
        <div class="track-index">
          <span v-show="!isHovering" class="track-count">{{ index }}</span>
          <v-btn v-show="isHovering" icon variant="contained-text" size="small" color="primary" @click.stop="play">
            <v-icon size="small">{{ mdiPlay }}</v-icon>
          </v-btn>
        </div>
        <div class="track-first">
          <v-img
            v-if="type !== 'album'"
            :src="albumCover"
            max-height="40"
            max-width="40"
            class="rounded"
            :lazy-src="placeholderUrl"
            :aspect-ratio="1"
          />
          <div class="track-info">
            <v-list-item-title class="line-clamp-1" v-text="track.name" />
            <v-list-item-subtitle>
              <artists-link :artists="artists" class="line-clamp-1" />
            </v-list-item-subtitle>
          </div>
        </div>
        <div v-if="type !== 'album'" class="track-second">
          <router-link :to="`/album/${album.id}`" class="text-subtitle-2 text-onSurface line-clamp-2">
            {{ album.name }}
          </router-link>
        </div>
        <div class="track-third">
          <v-btn v-visible="liked || isHovering" size="small" icon variant="text" @click.prevent="toggleLike">
            <v-icon size="small" :color="liked ? 'primary' : ''">{{ liked ? mdiHeart : mdiHeartOutline }}</v-icon>
          </v-btn>
          <!--        <like-toggle :id="track.id" />-->
          <div class="track-duration">
            {{ formatDuring(track.dt || track.duration || 0) }}
          </div>
          <v-btn
            v-visible="isHovering"
            icon
            color="primary"
            variant="contained-text"
            size="small"
            @click.prevent="openMenu"
          >
            <v-icon size="small">
              {{ mdiDotsHorizontal }}
            </v-icon>
          </v-btn>
        </div>
      </div>
    </v-list-item>
  </v-hover>
</template>

<style scoped lang="scss">
.track-item {
  display: grid;
  grid-gap: 16px;
  align-items: center;
  height: 56px;
  cursor: pointer;
  transition: background-color 0.25s ease;
  grid-template-columns: [index] 40px [first] 3fr [second] 2fr [last] minmax(160px, 1fr);
  &.album-item {
    grid-template-columns: [index] 40px [first] 4fr [last] minmax(160px, 1fr);
  }
  &:hover {
    background-color: rgba(var(--v-theme-surfaceVariant), 0.5);
  }
  .track-index {
    .track-count {
      display: flex;
      align-items: center;
      justify-content: center;
    }
  }
  .track-first {
    display: flex;
    align-items: center;
    gap: 16px;
  }
  .track-second {
    a {
      text-decoration: none;
      &:hover {
        text-decoration: underline;
      }
    }
  }
  .track-third {
    display: flex;
    gap: 16px;
    align-items: center;
    justify-content: space-between;
  }
}
.unavailable {
  cursor: initial;
  .track-cover {
    filter: opacity(0.6) grayscale(1);
  }
  .track-index,
  .track-info,
  .track-second,
  .track-third {
    opacity: 0.6;
  }
}
</style>

// src/components/TrackItem.tsx
import { useMemo, useState } from 'react'
import { alpha, useTheme } from '@mui/material/styles'
import Box from '@mui/material/Box'
import { css, cx } from '@emotion/css'
import { AnimatePresence, motion } from 'framer-motion'
import { IconButton, Typography } from '@mui/material'
import PlayIcon from '@mui/icons-material/PlayArrow'
import FavoriteIcon from '@mui/icons-material/Favorite'
import FavoriteBorderIcon from '@mui/icons-material/FavoriteBorder'
import MoreHorizIcon from '@mui/icons-material/MoreHoriz'
import AlbumLink from '@/components/links/album'
import { formatDuring, sizeOfImage } from '@/util/fn'
import ArtistLink from '@/components/links/artist'
import Image from '@/components/Image'
import { useLikeTrack } from '@/hooks/useLike'
import { Track } from '@/types'
import { usePlayerStore } from '@/store/player'
import Wave from '@/components/Wave'
import { useUserStore } from '@/store/user'
import useUser from '@/hooks/useUser'

export default function TrackItem({ track, onPlay, onContextMenu, index }: {
  index?: number
  track: Track
  onPlay: (track: Track) => void
  onContextMenu?: (e: React.MouseEvent<HTMLElement, MouseEvent>, track: Track) => void
}) {
  const [isHovering, setIsHovering] = useState(false)
  const { isLiked, toggleLike } = useLikeTrack()
  const { account } = useUserStore()
  const { track: current, playing } = usePlayerStore()
  const theme = useTheme()
  const liked = isLiked(track.id)
  const isCurrent = useMemo(() => {
    return current?.id === track.id
  }, [current, track])

  const { logged, isVip } = useUser()

  const available = useMemo(() => {
    if (track.fee === 1) {
      if (logged && isVip) {
        return {
          enable: true,
        }
      }
      else {
        return {
          enable: false,
          text: 'VIP用户可用',
        }
      }
    }
    else if (track.fee === 4) {
      return {
        text: '付费专辑，先购买',
        enable: false,
      }
    }
    else if (track.noCopyrightRcmd) {
      return {
        text: '无版权',
        enable: false,
      }
    }
    else {
      return {
        enable: true,
      }
    }
  }, [isVip, logged])
  return <Box
    sx={{
      'transition': 'background-color .35s ease',
      'color': isCurrent ? theme.palette.primary.main : (available?.enable ? null : alpha(theme.palette.onSurface.main, 0.4)),
      '&:hover': {
        bgcolor: alpha(theme.palette.surfaceVariant.main, 0.2),
      },
    }}
    title={available?.enable ? '' : available.text}
    className={
      cx('grid grid-cols-3 gap-4 px-2 h-16 items-center cursor-pointer mb-1 rounded-lg', css`grid-template-columns: 1fr 1fr [last] 140px;`)
    } onMouseEnter={() => setIsHovering(true)}
    onMouseLeave={() => setIsHovering(false)}
    onContextMenu={e => onContextMenu && onContextMenu(e, { ...track, liked })}
  >
    <div className='flex gap-2'>
      {
        index !== undefined && <div className='w-6 flex flex-shrink-0 justify-center items-center'>{ isCurrent ? <Wave animate={playing}/> : `${index}`.padStart(2, '0') }</div>
      }
      <div className='h-12 w-12 flex-shrink-0 relative'>
        <div className='h-full w-full rounded-xl overflow-hidden'>
          <Image src={sizeOfImage(track.al?.picUrl, 128)}/>
        </div>
        <AnimatePresence>
          {
            isHovering && <motion.div className='absolute top-0 h-12 w-12 flex justify-center items-center'
                                      initial={{ opacity: 0, transform: 'translateY(10px)' }}
                                      animate={{ opacity: 1, transform: 'translateX(0px)' }}
                                      exit={{ opacity: 0, transform: 'translateY(10px)' }}
                                      transition={{
                                        duration: 0.25,
                                        ease: [0.34, 1.56, 0.64, 1],
                                      }}
              >
                  <IconButton onClick={() => onPlay(track)}><PlayIcon color='primary'/></IconButton>
              </motion.div>
          }
        </AnimatePresence>
      </div>
      <div className='flex flex-col justify-center'>
        <Typography className='line-clamp-1' variant='body1'>{track.name}</Typography>
        <Typography className='line-clamp-1' variant='caption' component={'div'}>
          {track.ar && <ArtistLink artist={track.ar}/>}
        </Typography>
      </div>
    </div>

    <Typography className='line-clamp-1' variant='body2' component={'div'}>{track.al && <AlbumLink album={track.al}/>}</Typography>

    <div className='flex justify-between items-center'>
      <div className='h-11 w-11'>
        {
          (isHovering || liked) && <motion.div
                initial={{
                  opacity: 0, transform: 'translateY(12px)',
                }}
                animate={{
                  opacity: 1, transform: 'translateY(0px)',
                }}
                transition={{
                  duration: 0.25,
                  ease: [0.34, 1.56, 0.64, 1],
                }}
            >
                <IconButton sx={{ p: 1.5 }} onClick={() => {
                  toggleLike(track.id, liked)
                }}>{
                  liked ? <FavoriteIcon fontSize='small'/> : <FavoriteBorderIcon fontSize='small'/>
                } </IconButton>

            </motion.div>
        }

      </div>
      <Typography variant='body2'>{formatDuring(track.dt)}</Typography>
      <div className='h-11 w-11'>
        {
          isHovering && <motion.div
                initial={{
                  opacity: 0, transform: 'translateY(12px)',
                }}
                animate={{
                  opacity: 1, transform: 'translateY(0px)',
                }}
                transition={{
                  duration: 0.25,
                  ease: [0.34, 1.56, 0.64, 1],
                }}
            >
                <IconButton sx={{ p: 1.5 }} onClick={e => onContextMenu && onContextMenu(e, track)}><MoreHorizIcon fontSize='small' /></IconButton>

            </motion.div>
        }

      </div>

    </div>
  </Box>
}
