// packages/renderer/src/components/Wave.vue
<script lang="ts" setup>
// eslint-disable-next-line vue/no-setup-props-destructure
const props = defineProps<{
  playing?: boolean
}>()
// coding here
const delay = ['-100ms', '-500ms', '-1100ms', '-900ms', '-700ms']
</script>
<template>
  <div class="d-flex wave">
    <div
      v-for="i in 5"
      :key="i"
      class="wave-item bg-primary animation"
      :style="{
        animationDelay: delay[i],
        animationPlayState: playing ? 'running' : 'paused',
      }"
    ></div>
  </div>
</template>
<style scoped lang="scss">
.wave {
  height: 14px;
  width: 18px;
  gap: 2px;
  &-item {
    flex: 1;
    border-radius: 0px;
  }
  .animation {
    transform-origin: bottom;
    animation: wave 0.8s ease-in-out infinite;
  }
}
@keyframes wave {
  0% {
    transform: scaleY(1);
  }
  50% {
    transform: scaleY(0.2);
  }
  100% {
    transform: scaleY(1);
  }
}
/* scoped css */
</style>

// src/components/Wave.tsx
import { css, cx, keyframes } from '@emotion/css'
import {useTheme} from "@mui/material";

const wave = keyframes`
    0% { transform: scaleY(1) }
    50% { transform: scaleY(0.2) }
    100% { transform: scaleY(1)}
  `
const animation = css`
  transform-origin: bottom;
  animation: ${wave} 1s ease-in-out infinite;
`
const delay = ['-100ms', '-500ms', '-1200ms', '-1000ms', '-700ms']

const Wave = ({ animate }: { animate: boolean }) => {
  const theme = useTheme()
  return (
    <div className='grid h-3 flex-shrink-0 grid-cols-5 items-end gap-0.5'>
      {[...new Array(5).keys()].map(i => (
        <div
          key={i}
          className={cx('h-full w-0.5', animation)}
          style={{
            borderRadius: 1,
            backgroundColor: theme.palette.primary.main,
            animationDelay: delay[i],
            animationPlayState: animate ? 'running' : 'paused',
          }}
        ></div>
      ))}
    </div>
  )
}

export default Wave
