// packages/renderer/src/components/layout/WindowControl.vue
<template>
  <div class="window-actions no-drag-area">
    <v-btn size="small" variant="text" class="action-item" @click="handleMinimize">
      <v-icon>
        {{ mdiWindowMinimize }}
      </v-icon>
    </v-btn>
    <v-btn size="small" variant="text" class="action-item" @click="handleToggleMaximize">
      <v-icon>
        {{ windowState === WindowState.MAXIMIZED ? mdiWindowRestore : mdiWindowMaximize }}
      </v-icon>
    </v-btn>
    <v-btn size="small" variant="text" class="action-item action-close" @click="handleClose">
      <v-icon>
        {{ mdiWindowClose }}
      </v-icon>
    </v-btn>
    <v-dialog v-model="showAlert" persistent>
      <v-card class="pt-4 pb-2" rounded="xl" color="surface" width="90vw" max-width="350">
        <div class="d-flex justify-center">
          <v-icon color="secondary">
            {{ mdiExitToApp }}
          </v-icon>
        </div>
        <v-card-title class="text-center">{{ $t('message.exit_tip') }}</v-card-title>
        <v-card-title>
          <v-radio-group :model-value="exitMode" hide-details>
            <v-radio
              color="primary"
              :value="ExitMode.minimize"
              :label="$t('message.exit_min')"
              @click="exitMode = ExitMode.minimize"
            ></v-radio>
            <v-radio
              color="primary"
              :value="ExitMode.exit"
              :label="$t('message.exit_direct')"
              @click="exitMode = ExitMode.exit"
            ></v-radio>
          </v-radio-group>
          <v-checkbox v-model="reminder" color="primary" hide-details :label="$t('message.reminder')"></v-checkbox>
        </v-card-title>

        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn color="primary" variant="text" @click="showAlert = false"> {{ $t('common.cancel') }} </v-btn>
          <v-btn color="primary" variant="text" @click="confirmExit"> {{ $t('common.confirm') }} </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </div>
</template>

<script setup lang="ts">
import {
  mdiCheckboxBlankOutline as mdiWindowMaximize,
  mdiClose as mdiWindowClose,
  mdiExitToApp,
  mdiMinus as mdiWindowMinimize,
  mdiWindowRestore,
} from '@mdi/js'
import { useIpcRenderer } from '@vueuse/electron'
import { storeToRefs } from 'pinia'

import { useAppStore } from '@/store/app'
import { ExitMode, useSettingStore } from '@/store/setting'
import { WindowState } from '@/util/enum'

const settingStore = useSettingStore()
const appStore = useAppStore()
const ipcRenderer = useIpcRenderer()
const { windowState } = storeToRefs(appStore)
const showAlert = ref(false)
const exitMode = ref(ExitMode.minimize)
const reminder = ref(false)

function handleMinimize() {
  ipcRenderer.invoke(WindowState.MINIMIZED)
}
function handleToggleMaximize() {
  if (windowState.value === WindowState.MAXIMIZED) {
    ipcRenderer.invoke(WindowState.NORMAL)
  } else {
    ipcRenderer.invoke(WindowState.MAXIMIZED)
  }
}
function handleClose() {
  if (settingStore.exitMode === ExitMode.prompt) {
    showAlert.value = true
  } else if (settingStore.exitMode === ExitMode.minimize) {
    ipcRenderer.invoke(WindowState.MINIMIZEDTRAY)
  } else if (settingStore.exitMode === ExitMode.exit) {
    ipcRenderer.invoke(WindowState.CLOSED)
  }
}
async function confirmExit() {
  if (reminder.value) {
    settingStore.exitMode = exitMode.value
  } else {
    settingStore.exitMode = ExitMode.prompt
  }
  showAlert.value = false
  if (exitMode.value === ExitMode.minimize) {
    ipcRenderer.invoke(WindowState.MINIMIZEDTRAY)
  } else if (exitMode.value === ExitMode.exit) {
    ipcRenderer.invoke(WindowState.CLOSED)
  }
}
</script>

<style lang="scss">
.window-actions {
  display: flex;
  align-items: center;
  > .action-item {
    &:hover {
      background: rgb(var(--v-theme-surfaceVariant));
    }
  }
  .action-close {
    transition: all 0.25s;
    &:hover {
      color: #fff;
      background: rgb(232, 17, 35);
    }
  }
}
</style>

// src/components/WindowControl.tsx
import { useState } from 'react'
import { ipcRenderer } from 'electron'
import { WindowState } from '@shared/types'
import {
  Button,
  Checkbox,
  Dialog,
  DialogActions,
  DialogContent,
  FormControl, FormControlLabel, Radio,
  RadioGroup, Typography,
} from '@mui/material'
import { ExitMode, useSettingStore } from '@/store/setting'
import { useAppStore } from '@/store/app'
import './windowcontrol.scss'

export default function WindowControl() {
  const { exitMode, setExitMode } = useSettingStore()
  const { windowState } = useAppStore()
  const [openAlert, setAlert] = useState(false)
  const [remember, setRemember] = useState(false)
  const [exit, setExit] = useState(ExitMode.minimize)
  function handleMinimize() {
    ipcRenderer.invoke(WindowState.MINIMIZED)
  }
  function handleToggleMaximize() {
    if (windowState === WindowState.MAXIMIZED)
      ipcRenderer.invoke(WindowState.NORMAL)
    else
      ipcRenderer.invoke(WindowState.MAXIMIZED)

  }
  function handleClose() {
    if (exitMode === ExitMode.prompt)
      setAlert(true)

    else if (exitMode === ExitMode.minimize)
      ipcRenderer.invoke(WindowState.MINIMIZEDTRAY)
    else if (exitMode === ExitMode.exit)
      ipcRenderer.invoke(WindowState.CLOSED)

  }
  async function confirmExit() {
    if (remember)
      setExitMode(exit)
    else
      setExitMode(ExitMode.prompt)

    setAlert(false)
    if (exit === ExitMode.minimize)
      ipcRenderer.invoke(WindowState.MINIMIZEDTRAY)
    else if (exit === ExitMode.exit)
      ipcRenderer.invoke(WindowState.CLOSED)

  }
  return <div className="traffic-lights no-drag-area">
            <button id="close" className="traffic-light traffic-light-close" onClick={handleClose}></button>
            <button id="minimize" className="traffic-light traffic-light-minimize" onClick={handleMinimize}></button>
            <button id="maximize" className="traffic-light traffic-light-maximize" onClick={handleToggleMaximize}></button>
    <Dialog sx={{
      '& .MuiPaper-root': {
        borderRadius: 6,
      },
    }} open={openAlert} onClose={() => setAlert(false)}>
      <DialogContent>
        <div className='flex flex-col'>
          <FormControl size='small'>
            <RadioGroup
             value={exit}
             onChange={
               (event: React.ChangeEvent<HTMLInputElement>) => {
                 setExit(Number((event.target as HTMLInputElement).value))
               }
             }
            >
              <FormControlLabel value={ExitMode.exit} control={<Radio />} label="直接关闭" />
              <FormControlLabel value={ExitMode.minimize} control={<Radio />} label="最小化到系统托盘" />
            </RadioGroup>
          </FormControl>
        </div>
        <Checkbox size='small' value={remember} onChange={(event: any, v) => {
          setRemember(v)
        }} /><Typography variant='caption'>记住我的选择</Typography>
      </DialogContent>
      <DialogActions>
        <Button onClick={() => setAlert(false)}>取消</Button>
        <Button onClick={() => confirmExit()}>确认</Button>
      </DialogActions>
    </Dialog>
  </div>
}
