// src/pages/setting/components/Theme.vue
<template>
  <app-settings-group v-model="appearance" title="common.theme" :items="appearanceItems" />
  <app-settings-group v-model="color" title="common.theme_color" :items="colorItems" />
  <v-btn
    fixed
    bottom
    right
    class="align-self-end text-capitalize mt-2"
    color="primaryContainer"
    :style="{
      position: 'fixed',
      right: '16px',
      bottom: '78px',
      borderRadius: '16px',
      height: '64px',
      zIndex: 1,
      transtion: 'all 0.3s ease-in-out',
    }"
    @click="handleCustomPalette"
  >
    <v-icon size="large">
      {{ mdiPalette }}
    </v-icon>
  </v-btn>
  <input v-show="false" ref="upload" type="file" accept="image/png,image/jpeg,image/webp" @change="handleChange" />
  <v-dialog v-model="customPalette">
    <v-card color="surfaceVariant" rounded="xl" class="py-4 pb-6 px-6 align-self-center">
      <div class="d-flex justify-center">
        <v-icon color="secondary" size="x-large">
          {{ mdiPalette }}
        </v-icon>
      </div>
      <div class="mt-3 d-flex flex-row gap-4 justify-center">
        <v-card
          variant="flat"
          height="128"
          width="128"
          rounded="lg"
          class="d-flex justify-center align-center bg-onSurfaceVariant"
          @click="handleColor"
        >
          <v-icon size="x-large">{{ mdiSelectColor }}</v-icon>
          <v-tooltip activator="parent" location="bottom" open-delay="100">
            {{ t('common.gen_from_color') }}
          </v-tooltip>
        </v-card>
        <v-card
          variant="flat"
          height="128"
          width="128"
          rounded="lg"
          class="d-flex justify-center align-center bg-onSurfaceVariant"
          @click="handleImage"
        >
          <v-icon size="x-large">{{ mdiImagePlus }}</v-icon>
          <v-tooltip activator="parent" location="bottom" open-delay="100">
            {{ t('common.gen_from_image') }}
          </v-tooltip>
        </v-card>
      </div>
    </v-card>
  </v-dialog>
  <v-dialog v-model="colorPalette">
    <v-card color="surfaceVariant" rounded="xl" class="py-4 pb-6 px-6 align-self-center" min-width="300">
      <v-card-title>{{ t('common.gen_color_value') }}</v-card-title>
      <div class="mt-3 d-flex flex-column gap-4 justify-center">
        <v-text-field v-model="colorValue" variant="filled" hide-details></v-text-field>
        <v-btn rounded="pill" variant="flat" color="primary" @click="handleColorChange">{{
          t('common.confirm')
        }}</v-btn>
      </div>
    </v-card>
  </v-dialog>
</template>

<script lang="ts" setup>
import {
  mdiDesktopTowerMonitor,
  mdiImagePlus,
  mdiPalette,
  mdiSelectColor,
  mdiWeatherNight,
  mdiWhiteBalanceSunny,
} from '@mdi/js'
import { storeToRefs } from 'pinia'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { useToast } from 'vue-toastification'

import { useDynamicChangeTheme } from '@/hooks/useTheme'
import { generateVuetifyTheme } from '@/plugins/vuetify'
import type { APPEARANCE } from '@/store/setting'
import { useSettingStore, WallpaperColor } from '@/store/setting'

import AppSettingsGroup from './Group.vue'
const { t } = useI18n()
const setting = useSettingStore()
const { customTheme, wallpaperColor } = storeToRefs(setting)
const toast = useToast()
const { applyTheme } = useDynamicChangeTheme()
const upload = ref<HTMLInputElement>()
const customPalette = ref(false)
const colorPalette = ref(false)
const colorValue = ref('')
const appearanceItems = computed(() => [
  {
    text: 'common.light',
    icon: mdiWhiteBalanceSunny,
    value: 'light',
  },
  {
    value: 'dark',
    text: 'common.dark',
    icon: mdiWeatherNight,
  },
  {
    value: 'system',
    text: 'common.auto',
    icon: mdiDesktopTowerMonitor,
  },
])

const defaultThemes = [
  {
    icon: mdiPalette,
    value: WallpaperColor.RedSandDunes,
    text: 'theme.RedSandDunes',
  },
  {
    icon: mdiPalette,
    value: WallpaperColor.GreenMountainTop,
    text: 'theme.GreenMountainTop',
  },
  {
    icon: mdiPalette,
    value: WallpaperColor.OrangeDesert,
    text: 'theme.OrangeDesert',
  },
  {
    icon: mdiPalette,
    value: WallpaperColor.BlueMountains,
    text: 'theme.BlueMountains',
  },
  {
    icon: mdiPalette,
    value: WallpaperColor.GreenRockyMountains,
    text: 'theme.GreenRockyMountains',
  },
]
const colorItems = computed(() => {
  if (customTheme.value.length) {
    return [
      ...defaultThemes,
      {
        icon: mdiPalette,
        value: 'Customize',
        text: 'theme.Customize',
      },
    ]
  }
  return [...defaultThemes]
})
const appearance = computed({
  get() {
    return setting.appearance
  },
  set(value: APPEARANCE) {
    setting.appearance = value
  },
})

const color = computed({
  get() {
    return wallpaperColor.value
  },
  set(value: WallpaperColor) {
    wallpaperColor.value = value
  },
})
function handleCustomPalette() {
  customPalette.value = true
}
function handleColor() {
  customPalette.value = false

  colorPalette.value = true
}
function handleImage() {
  upload.value?.click()
  customPalette.value = false
}
async function handleChange(e: Event) {
  const { files = [] } = e.target as HTMLInputElement
  if (files?.length) {
    if (files[0].size > 2 * 1024 * 1024) {
      toast.error(t('message.pic_limit'))
      return
    }
    try {
      const objectURL = URL.createObjectURL(files[0])
      const image = new Image()
      image.src = objectURL
      applyCustomTheme(image)
    } catch (e) {
      console.log(e)
    }
  }
}
async function handleColorChange() {
  if (colorValue.value) {
    applyCustomTheme(colorValue.value)
  }
  colorPalette.value = false
}
async function applyCustomTheme(value: string | HTMLImageElement) {
  try {
    const newThemes = await generateVuetifyTheme(value, 'Customize')
    applyTheme(newThemes)
    // store customize theme in localstorage
    customTheme.value = newThemes
    color.value = WallpaperColor.Customize
  } catch (e) {
    console.log(e)
  }
}
</script>

// apps/client/src/pages/setting/Theme.tsx
import Brightness4Icon from '@mui/icons-material/Brightness4'
import BrightnessHighIcon from '@mui/icons-material/BrightnessHigh'
import BrightnessAutoIcon from '@mui/icons-material/BrightnessAuto'
import LandscapeIcon from '@mui/icons-material/Landscape'
import { useTranslation } from 'react-i18next'
import { Button, Dialog, IconButton, Slider, TextField, Tooltip, Typography } from '@mui/material'
import { alpha, useTheme } from '@mui/material/styles'
import { Box } from '@mui/system'
import PaletteIcon from '@mui/icons-material/Palette'
import ColorLensOutlinedIcon from '@mui/icons-material/ColorLensOutlined'
import { forwardRef, useImperativeHandle, useRef, useState } from 'react'
import { useSnackbar } from 'notistack'
import Group from '@/components/Group'
import { APPEARANCE, THEME_COLOR, useSettingStore } from '@/store/setting'
import Col from '@/components/Col'
import { useContextMenu } from '@/hooks/useContextMenu'
import { generateMUITheme } from '@/plugins/theme'
import { fileToDataURL } from '@/util/fn'

const GenerateByImage = forwardRef(({ onApplyTheme }: { onApplyTheme: (link: string) => void }, ref) => {
  const uploadRef = useRef<HTMLInputElement>()
  const { enqueueSnackbar } = useSnackbar()
  const { t } = useTranslation()
  const onChange = (e: any) => {
    const { files = [] } = e.target
    if (files?.length) {
      if (files[0].size > 2 * 1024 * 1024) {
        enqueueSnackbar(t('message.pic_limit'))
        return
      }
      try {
        fileToDataURL(files[0]).then((res) => {
          onApplyTheme(res as string)
        })
      }
      catch (e) {
        console.error(e)
      }
    }
  }
  useImperativeHandle(ref, () => {
    return {
      open: () => {
        uploadRef.current?.click()
      },
    }
  }, [])
  return <input style={{
    display: 'none',
  }} ref={uploadRef} type="file" accept="image/png,image/jpeg,image/webp" onChange={onChange} />
})

function GenerateByLink({ open, onClose, onApplyTheme, type }: { open: boolean; onClose: () => void; onApplyTheme: (link: string) => void; type: 'code' | 'link' }) {
  const theme = useTheme()
  const { t } = useTranslation()
  const { enqueueSnackbar } = useSnackbar()
  const [link, setLink] = useState('')

  const handleClose = () => {
    setLink('')
    onClose()
  }
  const generate = () => {
    if (link) {
      onApplyTheme(link)
      handleClose()
    }
    else {enqueueSnackbar('请先输入图片链接')}
  }

  return <Dialog sx={{
    '& .MuiPaper-root': {
      borderRadius: 8,
    },
  }}  open={open} onClose={handleClose} >
    <Box className='pt-5 pb-4 px-2 flex flex-col' sx={{
      bgcolor: theme.palette.surfaceVariant.main,
      color: theme.palette.onSurfaceVariant.main,
      minWidth: 320,
    }}>
      <div className='flex flex-col items-center mb-4 gap-1'>
        <PaletteIcon />
        <Typography variant='body1'>{t`main.setting.custom_theme`}</Typography>
      </div>

      <div className='px-3 my-3'>
        <TextField className='w-full' variant='outlined'  label={ type === 'code'  ? t`common.color_code` :  t`common.image_link`} value={link} onChange={(e: any) => {
          setLink(e.target.value)
        }} />
      </div>
      <div className='flex justify-end'>
        <Button variant='text' onClick={handleClose}>{t`common.cancel`}</Button>
        <Button variant='text' onClick={generate}>{t`common.confirm`}</Button>
      </div>
    </Box>
  </Dialog>
}


export default function ThemeSetting() {
  const { appearance, setAppearance, themeColor, fontSize, setThemeColor, setCustomTheme, setFontSize } = useSettingStore()
  const { t } = useTranslation()
  const { enqueueSnackbar } = useSnackbar()
  const theme = useTheme()
  const { openContextMenu } = useContextMenu()
  const [open, setOpen]  = useState(false)
  const [type, setType]  = useState<'code' | 'link'>('code')
  const byImageRef = useRef<{ open: () => void }>()

  const handThemeMore = (e: any) => {
    openContextMenu(e, [{
      type: 'item',
      label: t`main.setting.gen_by_image`,
      onClick: () => {
        setType('link')
        byImageRef.current?.open()
      },
    },
    {
      type: 'item',
      label: t`main.setting.gen_by_link`,
      onClick: () => {
        setType('link')
        setOpen(true)
      },

    },
    {
      type: 'item',
      label: t`main.setting.gen_by_code`,
      onClick: () => {
        setType('code')
        setOpen(true)
      },
    }])
  }
  function applyCustomTheme(val: string) {
    try {
      let source
      if (type === 'link') {
        const image = new Image()
        image.src = val
        image.crossOrigin = 'anonymous'
        source = image
      }
      else {
        source = val
      }

      generateMUITheme(source, 'Palette').then((res) => {
        setCustomTheme(res.palette)
        setThemeColor(THEME_COLOR.Customize)
      })
    }
    catch (e) {
      enqueueSnackbar(t`message.something_wrong`, { variant: 'error' })
    }

  }

  function handleFontSizeChange(e: Event, val: number | number[]) {
    console.log(val)
    if (typeof val === 'number')
      setFontSize(val)

  }
  return <div>
    <Col variant='caption' title={t`common.appearance`} className='mb-4'>
    <Group exclusive items={[{
      icon: <BrightnessHighIcon fontSize='small'/>,
      title: t`common.light`,
      value: APPEARANCE.LIGHT,
    },
    {
      icon: <Brightness4Icon fontSize='small' />,
      title: t`common.dark`,
      value: APPEARANCE.DARK,
    },
    {
      icon: <BrightnessAutoIcon fontSize='small' />,
      title: t`common.auto`,
      value: APPEARANCE.SYSTEM,
    },
    ]} value={appearance} onChange={setAppearance}></Group>
    </Col>
    <Col title={t`common.theme_color`} variant='caption' className='mb-4' more={
      <Tooltip title={t`main.setting.custom_theme`} placement='top'>
        <IconButton
          sx={{
            bgcolor: alpha(theme.palette.tertiaryContainer.main, theme.palette.action.activatedOpacity),
          }}
          color={'tertiary' as 'primary'}
          size='small'
          onClick={handThemeMore}
        >
          <ColorLensOutlinedIcon fontSize='small' />
        </IconButton>
      </Tooltip>

    }>
      <Group exclusive items={[
        {
          icon: <LandscapeIcon fontSize='small' />,
          value: THEME_COLOR.GreenRockyMountains,
          title: t`theme.GreenRockyMountains`,
        },
        {
          icon: <LandscapeIcon fontSize='small' />,
          value: THEME_COLOR.OrangeDesert,
          title: t`theme.OrangeDesert`,
        },
        {
          icon: <LandscapeIcon fontSize='small' />,
          value: THEME_COLOR.BlueMountains,
          title: t`theme.BlueMountains`,
        },
        {
          icon: <LandscapeIcon fontSize='small' />,
          value: THEME_COLOR.GreenMountainTop,
          title: t`theme.GreenMountainTop`,
        },
        {
          icon: <LandscapeIcon fontSize='small' />,
          value: THEME_COLOR.RedSandDunes,
          title: t`theme.RedSandDunes`,
        },
        {
          icon: <LandscapeIcon fontSize='small' />,
          value: THEME_COLOR.Customize,
          title: t`theme.Customize`,
        },
      ]} value={themeColor} onChange={setThemeColor}></Group>
    </Col>
    <Col title={t`common.font_size`} variant='caption'>
      <div className='w-1/3'>
        <Slider
          size='small'
          value={fontSize}
          step={2}
          marks
          min={10}
          max={20}
          onChange={handleFontSizeChange}
        ></Slider>
      </div>

    </Col>
    <GenerateByImage onApplyTheme={applyCustomTheme} ref={byImageRef} />
    <GenerateByLink open={open} onClose={() => setOpen(false)} onApplyTheme={applyCustomTheme} type={type} />
  </div>
}
