// apps/web/src/pages/Search.tsx
import { useTheme } from '@mui/material/styles'
import { Card, Typography } from '@mui/material'
import { useTranslation } from 'react-i18next'
import { useSearch } from '@/hooks/query/search'
import PageTransition from '@/components/PageTransition'
import Col from '@/components/Col'
import Cover from '@/components/cover/Cover'
import TrackList from '@/components/TrackList'
import ArtistCover from '@/components/cover/ArtistCover'
import GridRow from '@/components/GridRow'
import VideoCover from '@/components/cover/VideoCover'
import { GridType } from '@/hooks/useResponsiveGrid'
import SearchSkeleton from '@/components/skeleton/SearchSkeleton'
import useSearchParams from '@/hooks/useSearchParams'

export default function Search() {
  const { t } = useTranslation()
  const { searchParams } = useSearchParams()
  console.log(searchParams)
  const searchKeyword = searchParams.get('keyword')
  const { data, isLoading } = useSearch(searchKeyword)
  const theme = useTheme()
  return <PageTransition>
    {
      isLoading
        ? <SearchSkeleton />
        : <section className='flex flex-col gap-4 pr-2'>
        <div
          className='grid grid-cols-5 gap-4'
        >
          <Col title={t`common.search_hot`} variant='subtitle1' className='flex flex-col col-span-2'>
            <Card variant='outlined' sx={{
              flex: 1,
              bgcolor: theme.palette.surfaceVariant.main,
              color: theme.palette.onSurfaceVariant.main,
              borderRadius: 4,
              p: 2,
            }}>
              <GridRow singleLine rowType={GridType.B}>
                {
                  data?.result?.bestMatch?.map((i: any) => {
                    let content
                    if (i.type === 'artist') {
                      content = <ArtistCover compact data={i.object} key={i.object.id} />
                    }
                    else {
                      content = <Cover
                        data={i.object}
                        key={i.type}
                        type={i.type}
                        inset
                        noTitle
                      ></Cover>
                    }
                    return <div key={i.object.id} className='flex flex-col gap-4'>
                      {content}
                      <div className='flex flex-col items-center'>
                        <Typography variant='caption' className='line-clamp-2'>{ i.object.name }</Typography>
                        <Typography variant='caption'>{ i.type }</Typography>
                      </div>
                    </div>
                  })
                }
              </GridRow>
            </Card>
          </Col>
          {
            data?.result?.songs && <Col title={t`main.tracks`} variant='subtitle1' className='col-span-3'>
                  <TrackList tracks={data?.result?.songs} trackFrom={{ id: searchKeyword, name: '搜索页', type: 'search' }} />
              </Col>
          }
        </div>
        {
          data?.result?.artists?.length && <Col title={t`main.artists`} variant='subtitle1'>
                <GridRow>
                  {
                    data?.result?.artists.map(i => <ArtistCover data={i} key={i.id} />)
                  }
                </GridRow>
            </Col>
        }
        {
          data?.result?.albums?.length && <Col title={t`main.albums`} variant='subtitle1'>
                <GridRow>
                  {
                    data?.result?.albums.map(i => <Cover data={i} key={i.id} type='album' />)
                  }
                </GridRow>
            </Col>
        }
        {
          data?.result?.playlists?.length && <Col title={t`main.playlists`} variant='subtitle1'>
                <GridRow>
                  {
                    data?.result?.playlists.map(i => <Cover data={i} key={i.id} type='playlist' />)
                  }
                </GridRow>
            </Col>
        }
        {
          data?.result?.mvs?.length && <Col title={t`main.mvs`} variant='subtitle1'>
                <GridRow rowType={GridType.B}>
                  {
                    data?.result?.mvs.map(i => <VideoCover data={i} key={i.id} />)
                  }
                </GridRow>
            </Col>
        }
      </section>
    }

  </PageTransition>
}

// src/pages/search/index.vue
<script setup lang="ts">
import { reactive, ref, watchEffect } from 'vue'
import { useToast } from 'vue-toastification'

import { multiMatchSearch, search } from '@/api/music'
import { GridType } from '@/hooks/useResponsiveGrid'
import { usePlayer } from '@/player/player'
import type { Album, Artist, MV, Playlist, Track } from '@/types'
const toast = useToast()
const player = usePlayer()

const searchTypes = {
  song: { type: 1, limit: 4 },
  album: { type: 10, limit: 5 },
  artist: { type: 100, limit: 5 },
  playlist: { type: 1000, limit: 5 },
  mv: { type: 1004, limit: 3 },
}
interface BestMatch {
  type: 'artist' | 'playlist' | 'album'
  object: Artist | Playlist | Album
}

const loading = ref(false)
const state = reactive({
  artists: [] as Artist[],
  songs: [] as Track[],
  albums: [] as Album[],
  playlists: [] as Playlist[],
  mvs: [] as MV[],
  bestMatch: [] as BestMatch[],
})
const props = defineProps({
  keywords: {
    type: String,
    default: '',
  },
})

watchEffect(() => {
  if (props.keywords) {
    triggerSearch()
  }
})

async function triggerSearch() {
  if (!props.keywords) {
    return
  }
  loading.value = true
  try {
    const requests = Object.entries(searchTypes).map(([, val]) => {
      return search(props.keywords, {
        type: val.type,
        limit: val.limit,
      })
    })
    const [{ result: song }, { result: album }, { result: artist }, { result: playlist }, { result: mv }] =
      await Promise.all(requests)
    const { result: multi } = await multiMatchSearch(props.keywords)
    const orders = multi.orders.filter((i) => ['artist', 'playlist', 'album'].includes(i)) // 排除掉无关内容( new_mlog ?)

    state.bestMatch = orders.map((order) => ({
      object: multi[order]?.[0],
      type: order,
    }))
    state.songs = song.songs ?? []
    state.albums = album.albums ?? []
    state.artists = artist.artists ?? []
    state.playlists = playlist.playlists ?? []
    state.mvs = mv.mvs ?? []
  } catch (e) {
    toast.error('oops something wrong')
  } finally {
    loading.value = false
  }
}
function playMusic(trackId: number) {
  player.updatePlayerTrack(trackId)
}
</script>
<template>
  <v-sheet class="searching d-flex flex-column gap-6">
    <v-progress-linear v-if="loading" :indeterminate="loading" color="primary"></v-progress-linear>
    <h2 v-show="keywords" class="text-h5 font-weight-bold">{{ $t('common.search_type_1') }}: "{{ keywords }}"</h2>
    <v-row>
      <v-col v-if="state.bestMatch.length" cols="6" xl="4">
        <Col :title="$t('common.search_hot')">
          <v-card class="pa-4" color="surfaceVariant" rounded="lg" height="auto">
            <div class="d-flex gap-4">
              <div v-for="o in state.bestMatch" :key="o.type" :style="{ width: '135px' }">
                <Cover
                  :data="o.object"
                  :type="o.type"
                  max-height="135"
                  :rounded="o.type === 'artist' ? 'pill' : 'lg'"
                  :show-hover="o.type !== 'artist'"
                ></Cover>
                <div class="text-subtitle-2 d-flex flex-column align-center mt-4 gap-1">
                  <span class="font-weight-bold line-clamp-1">
                    {{ o.object.name }}
                  </span>
                  <span>{{ $t(`main.${o.type}s`) }}</span>
                </div>
              </div>
            </div>
          </v-card>
        </Col>
      </v-col>
      <v-col cols="6" xl="8">
        <Col v-if="state.songs.length" :title="$t('main.songs')">
          <track-list :tracks="state.songs" type="album" cover> </track-list>
        </Col>
      </v-col>
    </v-row>
    <Col v-show="state.artists.length" :title="$t('main.artists')">
      <CardRow>
        <ArtistsCover v-for="artist in state.artists" :key="artist.id" :artist="artist"></ArtistsCover>
      </CardRow>
    </Col>
    <Col v-show="state.albums.length" :title="$t('main.albums')">
      <CardRow>
        <Cover v-for="album in state.albums" :key="album.id" :data="album" type="album"></Cover>
      </CardRow>
    </Col>
    <Col v-show="state.playlists.length" :title="$t('main.playlists')">
      <CardRow>
        <Cover v-for="playlist in state.playlists" :key="playlist.id" :data="playlist" type="playlist"></Cover>
      </CardRow>
    </Col>
    <Col v-show="state.mvs.length" :title="$t('main.mvs')">
      <CardRow :grid-type="GridType.B">
        <VideoCover v-for="mv in state.mvs" :key="mv.id" :data="mv" />
      </CardRow>
    </Col>
  </v-sheet>
</template>
