// packages/renderer/src/pages/moods-genres/MoodsGenres.vue
<template>
  <Col v-for="(item, index) in items" :key="item.title" :class="index !== 0 ? 'mt-4' : void 0" :title="item.title">
    <v-row>
      <v-col v-for="tag in item.tags" :key="tag.name" cols="2">
        <m-tag :name="tag.name" :color="tag.color" />
      </v-col>
    </v-row>
  </Col>
</template>
<script lang="ts">
import { entries, groupBy, random } from 'lodash-es'
import { defineComponent } from 'vue'

import { getCatList } from '@/api/playlist'
import { getColorTable } from '@/util/metadata'

import type { Tag } from '../explore/Explore.vue'
import MTag from './Tag.vue'

export default defineComponent({
  name: 'MoodsGenres',
  components: {
    MTag,
  },
  data: () => ({
    items: [] as { title: string; tags: Tag[] }[],
    colors: Object.values(getColorTable() ?? {}) ?? [],
  }),
  created() {
    this.fetch()
  },
  methods: {
    async fetch() {
      const { sub, categories } = await getCatList()
      const items = sub.map((i: Tag) => {
        i.color = this.colors[random(0, this.colors.length)]
        return i
      })
      const group = groupBy(items, 'category') ?? {}
      this.items = entries(group).map(([k, v]) => ({
        title: categories[k],
        tags: v,
      }))
      this.items.unshift({
        title: '推荐',
        tags: [
          {
            color: this.colors[random(0, this.colors.length)],
            name: '官方',
          },
          {
            color: this.colors[random(0, this.colors.length)],
            name: '精品',
          },
          {
            color: this.colors[random(0, this.colors.length)],
            name: '推荐',
          },
        ],
      })
    },
  },
})
</script>

// src/pages/explore/MoodsGenres.tsx
import { useQuery } from '@tanstack/react-query'
import { entries, groupBy, random } from 'lodash-es'
import { useNavigate } from 'react-router-dom'
import PageTransition from '@/components/PageTransition'
import { getCatList } from '@/api/playlist'
import { HexColors } from '@/util/metadata'
import Col from '@/components/Col'
import GridRow from '@/components/GridRow'
import MdTag from '@/components/Tag'

const randomColor = () => HexColors[random(0, HexColors.length)]
export default function MoodsGenresPage() {
  const navigate = useNavigate()

  const { data, isLoading } = useQuery(['moodsgenres', 'cats'], async () => {
    const { sub, categories } = await getCatList()
    const items = sub.map((i: any) => {
      i.color = randomColor()
      return i
    })
    const group = groupBy(items, 'category') ?? {}
    let cats = []
    cats = entries(group).map(([k, v]) => ({
      title: categories[k],
      tags: v,
    }))
    cats.unshift({
      title: '推荐',
      tags: [
        {
          color: randomColor(),
          name: '官方',
        },
        {
          color: randomColor(),
          name: '精品',
        },
        {
          color: randomColor(),
          name: '推荐',
        },
      ],
    })
    return {
      cats,
    }
  }, {
    staleTime: 30 * 60 * 60 * 1000,
  })
  return <PageTransition>
    {
      data?.cats?.map((cat) => {
        return <Col variant='h6' title={cat.title} key={cat.title}>
          <GridRow>
            {
              cat.tags.map((tag) => {
                return <MdTag onClick={() => {
                  navigate(`/moods_and_genres/${tag.name}?color=${encodeURIComponent(tag.color)}`)
                }} key={tag.name} name={tag.name} tagcolor={tag.color} to={`${tag.name}`} />
              })
            }
          </GridRow>
        </Col>
      })
    }
  </PageTransition>
}
