// apps/client/src/components/toggle/likeToggle.tsx
import type { AnimationItem } from 'lottie-web'

import { IconButton, Tooltip } from '@mui/material'
import FavoriteIcon from '@mui/icons-material/Favorite'
import FavoriteBorderIcon from '@mui/icons-material/FavoriteBorder'
import { useState } from 'react'
import LottieIcon from '../LottieIcon'
import heart from '@/assets/lottie-assets/heart.json'
import { sleep } from '@/util/fn'
import { useUserStore } from '@/store/user'
import { useLikeTrack } from '@/hooks/useLike'
import { Track } from '@/types'

import { useLocalStore } from '@/store/local'

export function LikeToggle({
  id,
  size,
  color,
}: {
  id?: number
  size?: 'small' | 'medium' | 'large'
  color?: string
}) {
  const { favSong } = useUserStore()
  const { isLiked } = useLikeTrack()
  const liked = isLiked(id)
  const heartOptions = {
    animationData: heart,
    loop: false,
    autoplay: true,
  }
  const [heartAnim, setHeartAnim] = useState<AnimationItem | null>(null)
  const [showAnim, setShowAnim] = useState(false)

  function handleAnimation(animation: AnimationItem) {
    setHeartAnim(animation)
  }
  async function likeSong() {
    const _liked = liked
    const success = await favSong(id!, !_liked)
    if (!_liked && success) {
      setShowAnim(true)
      heartAnim?.goToAndPlay(0, true)
      await sleep(1000)
      setShowAnim(false)
    }
  }
  return (
    <Tooltip title={ liked ? '从喜欢的音乐移除' : '收藏到喜欢的音乐'} placement='top'>
    <IconButton
      className='no-drag-area'
      onClick={likeSong}
      sx={{ p: 0, height: size === 'small' ? 28 : 36, width: size === 'small' ? 28 : 36 }}
      color="error"
    >
      {showAnim
        ? (
        <LottieIcon
          option={heartOptions}
          height={size === 'small' ? 28 : 36}
          width={size === 'small' ? 28 : 36}
          animCreated={handleAnimation}
        ></LottieIcon>
          )
        : liked
          ? (
        <FavoriteIcon fontSize='small' />
            )
          : (
        <FavoriteBorderIcon fontSize='small' />
            )}
    </IconButton>
    </Tooltip>
  )
}


export function LocalLikeToggle({
  id,
  size,
  color,
}: {
  id: number
  size?: 'small' | 'medium' | 'large'
  color?: string
}) {
  const { likes, likeSong } = useLocalStore()

  const liked = !!likes.includes(id)

  const heartOptions = {
    animationData: heart,
    loop: false,
    autoplay: true,
  }
  const [heartAnim, setHeartAnim] = useState<AnimationItem | null>(null)
  const [showAnim, setShowAnim] = useState(false)

  function handleAnimation(animation: AnimationItem) {
    setHeartAnim(animation)
  }
  async function toggleSong() {
    const _liked = liked
    const success = await likeSong(id!, !_liked)
    if (!_liked && success) {
      setShowAnim(true)
      heartAnim?.goToAndPlay(0, true)
      await sleep(1000)
      setShowAnim(false)
    }
  }
  return (
    <Tooltip title={ liked ? '从本地喜欢的音乐移除' : '收藏到本地喜欢的音乐'} placement='top'>
      <IconButton
        className='no-drag-area'
        onClick={toggleSong}
        sx={{ p: 0, height: size === 'small' ? 28 : 36, width: size === 'small' ? 28 : 36 }}
        color="error"
      >
        {showAnim
          ? (
            <LottieIcon
              option={heartOptions}
              height={size === 'small' ? 28 : 36}
              width={size === 'small' ? 28 : 36}
              animCreated={handleAnimation}
            ></LottieIcon>
            )
          : liked
            ? (
              <FavoriteIcon fontSize='small' />
              )
            : (
              <FavoriteBorderIcon fontSize='small' />
              )}
      </IconButton>
    </Tooltip>
  )
}


export default function LikeToggleButton({
  track,
  size,
  color,
}: {
  track?: Track
  size?: 'small' | 'medium' | 'large'
  color?: string
}) {
  const isLocal = track?.source.fromType === 'local'
  if (isLocal)
    return <LocalLikeToggle id={track.id} color={color} size={size}></LocalLikeToggle>
  else
    return <LikeToggle id={track.id} color={color} size={size}></LikeToggle>


}

// src/components/toggle/likeToggle.vue
<template>
  <v-btn
    :density="size === 'small' ? 'comfortable' : 'default'"
    variant="text"
    icon
    :color="liked ? color ?? 'error' : ''"
    :size="size"
    @click="likeSong"
  >
    <v-icon v-show="!state.showAnim" :size="size" :color="liked ? color ?? 'error' : ''">{{
      liked ? mdiHeart : mdiHeartOutline
    }}</v-icon>
    <lottie-icon
      v-show="state.showAnim"
      ref="lottieIcon"
      :options="state.heartOptions"
      :height="size === 'small' ? 31 : 51"
      :width="size === 'small' ? 31 : 51"
      :style="{ position: 'relative', top: '-1.5px', left: size === 'small' ? '-1px' : '-1.5px' }"
      @anim-created="handleAnimation"
    ></lottie-icon>
    <v-tooltip activator="parent" location="top"> {{ t('common.fav', liked ? 0 : 1) }} </v-tooltip>
  </v-btn>
</template>
<script setup lang="ts">
import { mdiHeartOutline } from '@mdi/js'
import type { AnimationItem } from 'lottie-web'
import { useI18n } from 'vue-i18n'

import { useUserStore } from '@/store/user'
import { sleep } from '@/util/fn'
import { mdiHeart } from '@/util/icons'
import heart from '@/util/lottie-assets/heart.json'
const { t } = useI18n()

const userStore = useUserStore()
const props = defineProps<{
  id?: number
  size?: 'small' | 'default'
  color?: string
}>()

interface RootState {
  showAnim: boolean
  heartAnim: AnimationItem | null
  heartOptions: {
    animationData: any
    loop: boolean
    autoplay: boolean
  }
}
const state = reactive<RootState>({
  heartAnim: null,
  showAnim: false,
  heartOptions: {
    animationData: heart,
    loop: false,
    autoplay: false,
  },
})

const liked = computed(() => {
  return userStore.likes.includes(props.id!)
})
function handleAnimation(animation: AnimationItem) {
  state.heartAnim = animation
}
async function likeSong() {
  const _liked = liked.value
  const success = await userStore.favSong(props.id!, !liked.value)
  if (!_liked && success) {
    state.showAnim = true
    state.heartAnim?.goToAndPlay(0, true)
    await sleep(1000)
    state.showAnim = false
  }
}
</script>
